### ISSUE TITLE
Client stub - Allow login

### ISSUE THREAD

**Issue by qjhart** [ucd-library/aggie-experts#111]
v2.experts.library.ucdavis has a complete set of fcrepo and ES data.  We can use some of the services, and the kibana interface to investigate thsi data.  However, we need  to have a simple client in place, just to have a login to have access to fcrepo

**Comment by qjhart** [comment]
@UcDust I have started this at 

```bash
git clone --branch=qh-experts https://github.com/ucd-library/aggie-experts-deployment.git
```

The client is at [base-service/spa](https://github.com/ucd-library/aggie-experts/tree/c6d1406d24f0def47a191258fd9518db03d158c2/services/base-service/spa) like dams/fin/ucd-lib-client where I got most of the data.  Let me know if you can make heads of tails of this, and we'll see if it's worth doing in this sprint

**Comment by UcDust** [comment]
@qjhart @rakunkel-ucd 

I've tried to strip out a lot of the extra packages and code, and created a basic landing page with a `Sign In` link in the header nav and a link to fcrepo. There's an open PR for this now.

<img width="1724" alt="Screenshot 2023-08-17 at 13 22 16" src="https://github.com/ucd-library/aggie-experts/assets/103536473/b101ec60-c486-4cc0-b805-1cd2b7316545">

To build the client code after the cluster is up, you just need to go in the terminal to `/aggie-experts/services/base-service/spa/client` and run `npm run watch`. This starts webpack and builds the client code for various page bundles.
