### ISSUE TITLE
experts-cdl-users --group=431 --fusekiTmp

### ISSUE THREAD

**Issue by qjhart** [ucd-library/aggie-experts#162]
The `/users` API for Elements when set `detail=ref` will return with a user's identifiers.  This can also be done by `group` which we need to determine the lists of users to get for Aggie Experts.  You can set 1000 at a time in ref mode.  The [API docs](https://drive.google.com/file/d/1N-0GdAaIu8D8GdUa-YyyPxmzfjfO0wqb/view?usp=drive_link) describe some additional parameters like `group_membership`. You can also use individual identifiers as shown below.

We need a cmd-line tool to make these requests, and save them to a fuseki database, or to a file.    This can be used  to get all the individuals we need to get a complete set of people for Aggie Experts

An individual record, after xml2json, looks like this: 
```json
{
  "category": "user",
  "id": "42956",
  "proprietary-id": "10219597",
  "authenticating-authority": "UCTRUST",
  "username": "quinn@ucdavis.edu",
  "last-affected-when": "2023-08-21T12:59:42.293-07:00",
  "last-modified-when": "2022-09-24T08:24:32.013-07:00",
  "href": "https://oapolicy.universityofcalifornia.edu:8002/elements-secure-api/v5.5/users/42956",
  "created-when": "2019-09-12T09:35:28.347-07:00",
  "type-id": "1",
  "type-display-name": "Person",
  "type": "person",
  "api:relationships": {
    "href": "https://oapolicy.universityofcalifornia.edu:8002/elements-secure-api/v5.5/users/42956/relationships"
  }
}
```

We are only interested primarily in the identifiers.
```bash
http --session-read-only=ucd https://oapolicy.universityofcalifornia.edu:8002/elements-secure-api/v5.5/users ids==42956,95993,14856,14668 > sure.xml
xml2json sure.xml | jq '.feed.entry[]["api:object"]|{id,"proprietary-id",username}'
```
```json
{
  "id": "42956",
  "proprietary-id": "10219597",
  "username": "quinn@ucdavis.edu"
}
```

However, to be consistent with our schemes, this should look more like : 

``` json
{
"@id": "person:66356b7eec24c51f01e757af2b27ebb8",
"identifiers": [ 
        "ark:/87287/d7mh2m/user/42956",
        "ark:/87287/d7c08j/59937aff685275f56a6dc7e1d6fa02db" ]
}
``` 

Where the first is the Elements #, and the second is the md5 sum of the proprietary id.  Since we sometimes want clear text of these, there should be a flag on the tools that would include: 

```json 
{
"@id": "person:66356b7eec24c51f01e757af2b27ebb8",
"identifiers": [ 
        "ark:/87287/d7mh2m/user/42956",
        "ark:/87287/d7c08j/59937aff685275f56a6dc7e1d6fa02db",
        "quinn@ucdavis.edu"
 ]
}
``` 

Or similar.

You can also get users by their id as in:

```bash
http --session-read-only=ucd https://oapolicy.universityofcalifornia.edu:8002/elements-secure-api/v5.5/users ids==42956,95993,14856,14668 > sure.xml
xml2json sure.xml | jq '.feed.entry[]["api:object"]|{id,proprietary_id,username}'
```

Or by their usernames as in:

```bash
http --session-read-only=ucd https://oapolicy.universityofcalifornia.edu:8002/elements-secure-api/v5.5/users username==quinn@ucdavis.edu
```

**Comment by rakunkel-ucd** [comment]
Ready for a review

**Comment by rakunkel-ucd** [comment]
Usage: 
bin/experts.js cdl-users 42956,95993,14856,14668
bin/experts.js cdl-users --username=quinn@ucdavis.edu
bin/experts.js cdl-users --groups=431

**Comment by rakunkel-ucd** [comment]
Output file: data/users.jsonld
Creates new Fuseki dataset
