### ISSUE TITLE
AE - Person page design

### ISSUE THREAD

**Issue by UcDust** [ucd-library/aggie-experts#169]
Create the researcher / person page based on Figma designs, like-
<img width="444" alt="Screenshot 2023-09-20 at 12 02 48" src="https://github.com/ucd-library/aggie-experts/assets/103536473/e5883444-e8b5-4f3a-91ed-21466b0eb827">

The api currently exists at `/api/person/<personId>` to populate this page.

**Comment by UcDust** [comment]
@qjhart here's an issue to track the _Person_ page.

One item we discussed earlier was where to store the person profile images.

**Comment by UcDust** [comment]
@qjhart 

A few notes from our discussion earlier:

- There were a few spots the vivo: schema is showing up in the `person.contactInfo` array. For instance, `hasURL.cite:url`, `vivo:hasEmail`, `vivo:name`, `vivo:hasOrganizationalUnit`, `hasTitle.cite:title`.
- `contactInfo.hasOrganizationalUnit` and `contactInfo.hasTitle` both have `title` properties that we're going to change to `name` most likely.
- We're going to show `vcard-oap` records with `hasURL` and a `rank` of 20 under the _Websites_ section.
- We'll order the other contact card types by rank and display rank 1 under the _Roles_ section.
- We're going to add a flag into the contact items to indicate `visibility`.
- Even items that are not visible based on this flag, if they have a URL and rank of 20, we'll show them under the _Websites_ section.

**Comment by UcDust** [comment]
Some comments in the [Aggie Experts User Test document](https://docs.google.com/spreadsheets/d/1X2W-ohJwtblfGdXdA7lAJJn2sqKvS9tIEd8sR3aospY/edit#gid=0):

- [ ] Introduction should not show up as a header since it doesn;t have content. See Kimmy's mockup of Zhongli Pan (person/02984e04d789b10c5e2cf03cd85167c2
)
- [ ] Website icon is showing without any URL with it (similar for Email) (person/02f7461cdc009c374ba3aaeccca4ad93)
- [ ] How should spacing work when the webpage is resized (currently columns almost run into each other)
- [ ] ODR has the wrong website. Need a procedure for us to figure this out (person/0445f1ba36964affa6236c765038d539)
- [ ] Her website is redirecting to an AE subpage. But the true website is "under maintenance".  But also ODR has it as [https://org.ucdavis.edu/directory-search/ucdchangelab.com](https://www.google.com/url?q=https://org.ucdavis.edu/directory-search/ucdchangelab.com&sa=D&source=editors&ust=1695931330664369&usg=AOvVaw0j_bUlfAIDUfyN503XATDC). (person/048ea1bc8d46d630fe2031b283b7072b)
- [ ] We need to rethink calling author id links "Websites" when the websites wnd up listed under "Roles" (person/048ea1bc8d46d630fe2031b283b7072b)
- [ ] We need an "impersonate" functionality
- [ ] Non senate and Emeritus--shouldn't be in this dataset (person/068533776d5e363789d4dae2a9b21dd0)
- [ ] Email exists in ODR, but didn't come through on AE (person/0a0c0bc68341ef19d450271c2e6a0f94)
- [ ] Has email, viewable in ODR; not showing up in AE (person/0c5a30cfd479b1130febe09b90646d4d)

**Comment by UcDust** [comment]
@Vensberg @qjhart 

[This PR](https://github.com/ucd-library/aggie-experts/pull/196) should be merged in soon if not already. 

It should address some of the styling issues on the _About Me_ section for various data existing and not, and when viewing from smaller width screens or mobile.

It also includes updates to the _SEE ALL WORKS_ page, which lists 20 records per page and has pagination at the bottom. Also the works should be organized by date descending, then by title ascending. So works in the same year should be sorted alphabetically.

The download functionality hasn't been added yet to the person page, that will be my focus next.

**Comment by qjhart** [comment]
@Vensberg , sandbox has been updated.  If you can go through the [User Test](https://docs.google.com/spreadsheets/d/1X2W-ohJwtblfGdXdA7lAJJn2sqKvS9tIEd8sR3aospY/edit?usp=sharing) and remove comments that are no longer required, that would be great.  I'm re-assigning you to Q/A.  Can you strike out the finished items, or cut and paste the TODO's below

**Comment by Vensberg** [comment]
Data issues:
- [ ] Non senate and Emeritus--shouldn't be in this dataset (person/068533776d5e363789d4dae2a9b21dd0)
- [ ] Email exists in ODR, but didn't come through on AE (person/0a0c0bc68341ef19d450271c2e6a0f94); Has email, viewable in ODR; not showing up in AE (person/0c5a30cfd479b1130febe09b90646d4d); When an ODR record exists, but the email is in PPS, we lose it. Can we add the email from PPS?
- [ ] Error with person retrieval  (28ed0daef6cc0be019a360fec5de3d69)
- [ ] Doubled name 
In the data,
identifier
0 "ark:/87287/d7mh2m/user/80832"
1 "ark:/87287/d7c08j/5bff08450adc6ae6be9a13af73d8d1dc"
2 "person/47df28894f5d9417bec945e10bd7b9f4"
3 "person:47df28894f5d9417bec945e10bd7b9f4"
name
0 "Brett Snyder"
1 "Brett Synder"
hasName "person/47df28894f5d9417bec945e10bd7b9f4#name"
- [ ] She has two scopus ids, and the link string is concatenating them. Need to break them into two separate ids (or rethink how we treat author ids) (4cd517a7ee951054d259a4d08251be18)
- [ ] Has content in ucdlib:researchInterests, but is not rendered in the Introduction section (501fe9eb770b88ab37cc2942f3b1e7aa)
- [ ] Researcher Id is in the data but not displayed (68730aab9c15b24f2c03c0aa42f7580d)

**Comment by Vensberg** [comment]
- [ ] Citations do not combine data from sources: there are missing volumes and issue numbers, pages. For example, "ark:/87287/d7mh2m/relationship/10870784",  paper 3976034, has page and issue in the data (and are showing up in the combined data record), but the citation doesn;t render them. That seems to be the case with all citations I looked at. Citeproc issue?
- [ ] The work type reads "article-journal", "paper-conference". Can they be "journal article" and "conference paper"?
- [ ] This DOI does not resolve. [https://doi.org/10.3390/antibiotics11070963](https://www.google.com/url?q=https://doi.org/10.3390/antibiotics11070963&sa=D&source=editors&ust=1696629632881747&usg=AOvVaw22QNamXNKEGlS22xGlS-75). The publication is otherwise identical to [https://doi.org/10.3390/antibiotics11070954](https://www.google.com/url?q=https://doi.org/10.3390/antibiotics11070954&sa=D&source=editors&ust=1696629632881809&usg=AOvVaw1Mxx-4WjZPaPooCK7QhLGO), which resolves. @Vensberg 
- [ ] Let's have DOIs as active links

**Comment by Vensberg** [comment]
@UcDust , in the data rendering of the citations, can you change "pagination" to "page"? I think that will result in the pages being rendered.

**Comment by Vensberg** [comment]
Also, (n.d.) appears in the citation--that stands for no date, since the year is pulled out. Thoughts on how to make (n.d.) not show up?

**Comment by UcDust** [comment]
@Vensberg 

Sure, I can change 'pagination' to 'page' to see how that affects things.

I could also do a text replace to remove '(n.d.)' from the citation.

**Comment by qjhart** [comment]
If that works, then it needs to be an issue on the harvest, not in the
client.

**Comment by Vensberg** [comment]
@UcDust , yes, that it. Awesome!

**Comment by Vensberg** [comment]
@wrenaria , can you take a look at these two profiles:
https://sandbox.experts.library.ucdavis.edu/person/226d2dccfba4c2be04aedd4f9f942e42, https://sandbox.experts.library.ucdavis.edu/person/048ea1bc8d46d630fe2031b283b7072b
Currently, our main source for URLs is the online directory, so all website URLs are paired with Roles. The website column ends up containing mostly author ids. 
Eventually, people may start adding websites in Elements, and then those are supposed to appear under websites, like https://sandbox.experts.library.ucdavis.edu/person/66356b7eec24c51f01e757af2b27ebb8, but I expect that percentage to be low, at least for awhile. I wanted to check in with you to see if that aligns with your vision.

**Comment by wrenaria** [comment]
@Vensberg Maybe we should change the title to "Links" ? That might feel a little more general/accurate to the content than the word "Websites" for things like author IDs. What do you think? Otherwise, functionally I think this is okay.

**Comment by Vensberg** [comment]
@UcDust 
For "Help"
- [ ]  In the last question "How do I delete my profile" I'd like to change the wording for clarity. The [word doc](https://docs.google.com/document/d/1mvCuOP7339W7_DeHyC74HLSO7z4k1F_wy3k1TAhCYCQ/edit) is now edited to reflect that.
- [ ] I can't currently sign in, so the portion for MIV will get QA'ed when that is in place.
- [ ] Let's implement Kimmy's suggestion and change "Websites" to "Links" in the About Me section (both public and admin). This would also require changing the hover text over the edit button from "Edit websites" to "Edit links".
- [ ] For some reason, publication ark:/87287/d7mh2m/relationship/5921845 on Quinn's profile is still showing (n.d.) in the citation

**Comment by UcDust** [comment]
@Vensberg 
The grants/works pagination should be working now, specifically, when page 2+ is chosen, and then navigating back to a person or different person, the pagination should reset to the first page.

**Comment by Vensberg** [comment]
@UcDust , pagination for works looks good.

**Comment by UcDust** [comment]
@Vensberg 
You mentioned earlier to mention you in this task regarding the impersonate functionality on the expert page. Let me know how your testing goes!

**Comment by Vensberg** [comment]
@UcDust , here is a list of what works and two items that need to be looked at
- [x] Impersonate button works
- [x] Roles redirects to ODR
- [x] Links redirects to Elements
- [x] Profile page, grant download works
- [ ] About me (if shown with content) has an edit button and redirects to Elements (the mobile mockup has that, but not the desktop mockup. Can you apply the mobile one?)
- [x] Profile page-->works download: works
- [x] Edit grant --> hide grant redirects to Elements for now
- [ ] Edit grant --> Download: the csv is empty
- [x] Edit work --> hide work redirects to Elements for now
- [x] Edit work --> Download: works

I'll test this next. it has previously worked.
- [ ] RIS file works for MIV (VE still needs to check)

This is what I will test after more backend work is complete:
- [ ] Actual refresh date is in place (VE check with QH, defer to 2.1?)
- [ ] Profile page, grant download: there exists a column "Role" 
- [ ] Edit grant --> hide grant occurs on the spot
- [ ] Edit work --> hide work occurs on the spot. How are we going to check delete?

**Comment by UcDust** [comment]
@Vensberg this task could be used to QC the visibility of works and how grants appear on the expert page.

**Comment by Vensberg** [comment]
- [x] Visibility looks good 

Testing Matthew Bishop's citations: https://test.experts.library.ucdavis.edu/expert/a1b1a130a2577a7e781519306a4dd8c9
Impersonate
See: 2 additional works are hidden and may be accessed via editing mode 
But when I click on Edit, the header says "Manage My Works (246 Public, 0 Hidden)"
I'll try to hide "A Brief History and Overview of WISE", which is https://qa-oapolicy.universityofcalifornia.edu/viewobject.html?cid=1&id=3519829 in Elements.

Click on "eye" icon.
See "This record will be hidden from your profile and marked as "Internal" in the UC Publication Management System.

Are you sure you want to hide this work?"
Click on "Hide Work"

Appears in the interface as greyed out, with "crossed-out eye". 

In QA I see that
13 Feb 2024 14:37
Relationship set to Internal for the profile of Matthew Bishop.
 Aggie Experts

**Comment by Vensberg** [comment]
Checking rejection on the last one:
Works as expected.
I reversed that, now it is only invisible.

**Comment by Vensberg** [comment]
But now a refresh gave me a 404. The rejected work is gone (makes sense because there isn't an immediate pull from Elements QA).
Trying to reject another publication to see if I get 404 again: 
Beyond NVD: Cybersecurity meets the Semantic Web.
I get a 404 on Refresh.
Same thing for changing visibility (tested with SecTutor: An Intelligent Tutoring System for Secure Programming)

**Comment by Vensberg** [comment]
@UcDust , the visibility and rejection work great!

There are two related issues that I discovered in the process.

- [ ] When I make invisible or reject a work, and then refresh the page, I get a 404. A refreshed Manage My Works page is expected.
- [ ] The Manage My Works page correctly identifies the hidden works number (2). But the profile page of the authenticated user claims there are four. Does it count the rejected works, too?

**Comment by Vensberg** [comment]
Also, I tested reversing visibility on A Brief History and Overview of WISE. That reset the relationship to public in QA as expected

**Comment by UcDust** [comment]
@Vensberg @qjhart 

Regarding this issue you discovered:
```When I make invisible or reject a work, and then refresh the page, I get a 404. A refreshed Manage My Works page is expected.```

I think this is because when impersonating, refreshing the browser doesn't persist the impersonated user, and then the `edit` pages for works/grants throw the 404.

When thinking of how to address this, I wonder if we should even allow hiding/showing works/grants and rejecting works for a user when they're just impersonating. As in, should we only allow those changes to be made by the expert they belong to?

**Comment by UcDust** [comment]
@Vensberg 

The last 2 items you mentioned regarding the 404 page on refresh and the counts of visible vs hidden works should be addressed now, it's live on test.

**Comment by Vensberg** [comment]
@UcDust , when I impersonate and then refresh the page, the impersonation resets. Can you make it stay until canceled even after a refresh?

**Comment by UcDust** [comment]
@Vensberg You tried this on test? Sandbox doesn't have the fix yet, but refreshing on test seems to work for me.

**Comment by Vensberg** [comment]
@UcDust , I am on test. I can change visibility without breaking impersonation, but I can't refresh without that happening
