### ISSUE TITLE
AE - Search page design

### ISSUE THREAD

**Issue by UcDust** [ucd-library/aggie-experts#186]

**Comment by UcDust** [comment]
@Vensberg @qjhart 

The latest code should be deployed on sandbox for the search ui. 

Here's a sample download from a search-
[search-sample data.csv](https://github.com/ucd-library/aggie-experts/files/13034326/search-sample.data.csv)

We have a basic csv being generated with a row for each person that shows up in the search. Should we also somehow export works and grants data that match the search? If so, how would that show up in the download? (ie extra columns, how many rows per person, etc)

**Comment by Vensberg** [comment]
@UcDust The content of the CSV is described here https://github.com/ucd-library/aggie-experts/issues/77. 
I am going to add more context there and tag you.
