### ISSUE TITLE
Update Works for errors, and add labels

### ISSUE THREAD

**Issue by qjhart** [ucd-library/aggie-experts#189]
Some works have some errors in them, primarily

- [x] Some items have multipla issued dates
- [x] There is no adequate schema:name entry for the works

These need to be updated for the works to be properly searchable.

**Comment by qjhart** [comment]
Regarding multiple titles, etc. The problem stems from the fact that some sources have two entries for a single work. They then get added together.  The short fix for this is to not use that source.  However, that can lead to problems. For example, [this work](https://oapolicy.universityofcalifornia.edu/viewobject.html?cid=1&id=455311) has two items for fcrepo.  When we remove dimensions as a source however, the title that is associated is not the one that the publisher expects (via the DOI link)

**Comment by qjhart** [comment]
Further discussed in #195

**Comment by UcDust** [comment]
For works that fail to be parsed with the `citation-js` library, the citation APA text and RIS translation likely will not be generated. 

As such, the ui will show a message that there was an issue generating the citation, but still include a title. The RIS download will exclude the citation.
