### ISSUE TITLE
Need pull up name, websites, ? for person document

### ISSUE THREAD

**Issue by qjhart** [ucd-library/aggie-experts#190]
The Search API Requires that have have a proper name field for search output display.  Per conversation with @UcDust , we are going for format that schema:name field like: 

Hart, Quinn  §  Digital Applications Manager  UCD Library

In addition, for the search to be able to supply the required components for the CSV download, we need pulled up into the document:  `hasName`, `email`(best?), `AE landing page`, `websites`[;], `role`, `dept.`

**Comment by qjhart** [comment]
@Vensberg Is the notion here to pull the `email`, `role`, `website` from the best ODR entry? What's the fallback?

**Comment by Vensberg** [comment]
Yes, with the caveat that ODR sometimes masks an email in PPS, so or that the PPS should be used as a source. Also, if there are websites in Elements, those should be added. If no info exists, let's put "NA"

**Comment by qjhart** [comment]
> ...  that ODR sometimes masks an email in PPS, so then the PPS should be used as a source for email. 

What does that mean? don't use the best contact email?  That seems wrong to me.  It doesn't match directory which is what we try and follow.

**Comment by Vensberg** [comment]
There are cases in which the ODR entry does not have an email, but the PPS does. The online directory renders the email on the website. So, in those cases where the ODR email entry is empty, can you get the PPS email?

**Comment by qjhart** [comment]
@UcDust I've put this into Q/A for you to review,
