### ISSUE TITLE
Users can be added to Aggie Experts outside of the current scope

### ISSUE THREAD

**Issue by Vensberg** [ucd-library/aggie-experts#197]
We are adding users to Aggie Experts based on their job codes. However, there may be situations where an individual may want to be included earlier than a planned roll-out. We welcome Aggie Experts supporters, so we need a functionality that would allow us to add users on a custom basis.

**Comment by qjhart** [comment]
I have submitted an issue to CDL for guidance on adding new groups to the production system.  When we get that guidance, which I assume ill be `have at it`, We'll create an aggie experts group at Elements, I expect that will be a combo list as in

experts
\- senate (This will be an auto query)
\- federation (auto)
\- additional (a list we maintain) 

Then we can manage this on CDL, and always be up-to-date.

**Comment by Vensberg** [comment]
Thanks, @qjhart , this doesn't need to be ready for 2.0. I've been adding items to the backlog without milestones to indicate items we want to work on, but are not MVP.
