### ISSUE TITLE
Google  cloud project - aggie-experts

### ISSUE THREAD

**Issue by qjhart** [ucd-library/aggie-experts#207]
Google cloud services are **now provided** in the `aggie-experts` project.  You all should be able to view this via the cloud console. 

Regarding using the two configurations (aggie-experts, digital-ucdavis-edu).  This is the setup that I am using.

```bash
gcloud config configurations create aggie-experts
gcloud config set project aggie-experts 
# Set other parameters
```

This is an example of two configurations:

```
gcloud config configurations list

NAME           IS_ACTIVE  ACCOUNT             PROJECT              COMPUTE_DEFAULT_ZONE  COMPUTE_DEFAULT_REGION
aggie-experts  True       qjhart@ucdavis.edu  aggie-experts        us-west1-c            us-west1
digital        False      qjhart@ucdavis.edu  digital-ucdavis-edu  us-west1-c            us-west1
```

My more complete configuration looks like this: 

``` bash
gcloud config list 

[artifacts]
location = us-west1
repository = docker
[compute]
region = us-west1
zone = us-west1-c
[core]
account = qjhart@ucdavis.edu
disable_usage_reporting = True
project = aggie-experts

Your active configuration is: [aggie-experts]
```

Then you can test this with 

```bash
$ gsutil ls
gs://fcrepo-dev/
gs://fcrepo-prod/
gs://fcrepo-sandbox/
```

**Comment by qjhart** [comment]
@Vensberg / @rakunkel-ucd / @UcDust  please note the above information.  If it looks good,  just remove yourself.  Otherwise Id me on a comment below.  If you're the last one, then re-assign me, *and* close the issue

**Comment by qjhart** [comment]
@UcDust / @rakunkel-ucd / @Vensberg  We have now moved to the aggie-experts project.  You need to update your  configuration accordingly (described above) when working on aggie-experts.  I have tried to disable most of the old features (and your permissions) in `digital_ucdavis_edu` so you don't get too confused.

**Comment by rakunkel-ucd** [comment]
Got it.
