### ISSUE TITLE
Translate citation types in citation list results / apa

### ISSUE THREAD

**Issue by UcDust** [ucd-library/aggie-experts#208]
In the list of citations for works on the person page, we need to translate some citation types to something more easily readable. 

Below is a list of the types on the left with overrides on the right.

```json
{
    "article": "",
    "article-journal": "journal article",
    "article-magazine": "",
    "article-newspaper": "",
    "bill": "",
    "book": "",
    "broadcast": "",
    "chapter": "",
    "classic": "",
    "collection": "",
    "dataset": "",
    "document": "",
    "entry": "",
    "entry-dictionary": "",
    "entry-encyclopedia": "",
    "event": "",
    "figure": "",
    "graphic": "",
    "hearing": "",
    "interview": "",
    "legal_case": "",
    "legislation": "",
    "manuscript": "",
    "map": "",
    "motion_picture": "",
    "musical_score": "",
    "pamphlet": "",
    "paper-conference": "conference paper",
    "patent": "",
    "performance": "",
    "periodical": "",
    "personal_communication": "",
    "post": "",
    "post-weblog": "",
    "regulation": "",
    "report": "",
    "review": "",
    "review-book": "",
    "software": "",
    "song": "",
    "speech": "",
    "standard": "",
    "thesis": "",
    "treaty": "",
    "webpage": ""
}
```

**Comment by UcDust** [comment]
@Vensberg 

In #169 you mentioned-
_The work type reads "article-journal", "paper-conference". Can they be "journal article" and "conference paper"?_

In the description I've listed the possible types on the left with the 2 overrides filled in on the right. Would you mind reviewing those types and adding any other overrides you'd like?

As reference, this would be the first text under various works, like here-
<img width="1213" alt="Screenshot 2023-10-11 at 15 19 46" src="https://github.com/ucd-library/aggie-experts/assets/103536473/06e2f29e-8db7-407f-961a-e3c73489fd73">

**Comment by Vensberg** [comment]
So, we are pulling in only 4 types of works for now https://github.com/orgs/ucd-library/projects/23?pane=issue&itemId=40852631, the two that will get displayed differently, and book and chapter, which are single words, and look good. Eventually, when we start pulling everything, "article-magazine": "",     "article-newspaper": "",   "entry-dictionary": "",
    "entry-encyclopedia": "",  "post-weblog": "",  "review-book":  I'll ask for them to be flipped the same way, and for "motion_picture": "",     "musical_score": to drop the underscore. [Although, I don't think we'll get encyclopedia entries.]

**Comment by Vensberg** [comment]
@UcDust , in the data rendering of the citations, can you change "pagination" to "page"? I think that will result in the pages being rendered.
