### ISSUE TITLE
Supply Proper title Codes for PPS titles

### ISSUE THREAD

**Issue by UcDust** [ucd-library/aggie-experts#209]
Here's an example of the variability-

<img width="931" alt="Screenshot 2023-10-11 at 15 26 14" src="https://github.com/ucd-library/aggie-experts/assets/103536473/10b18cac-a3cc-496c-a859-2a151fc99651">

We could capitalize each word, but there are acronyms that should remain in all caps, and other characters occasionally separating groups of words, so the solution would need to be more elegant.

Also, @qjhart shared [this doc](https://docs.google.com/spreadsheets/d/1Zw2FV3CjZhTiGPrAH8E7X15VIXxZqt84F-5qYL_qykE/edit#gid=128868145) which has a mapping of title codes to titles snake cased, which was created in February. Perhaps we could use this mapping to generate titles, but how could we ensure that list of titles remains current?

**Comment by qjhart** [comment]
This [directory](https://github.com/ucd-library/aggie-experts/tree/dev/harvest/vocabularies/experts.ucdavis.edu%252Fucop) includes the information about title codes.  The current methodology uses title names from IAM as the title code.  Instead we need to use Aggie Expert title codes.   These need to  be reviewed, and we need to verify there is an entry for all the items in our user base.
