### ISSUE TITLE
An alternative scoring method for citations

### ISSUE THREAD

**Issue by qjhart** [ucd-library/aggie-experts#210]
### Discussed in https://github.com/ucd-library/aggie-experts/discussions/195

<div type='discussions-op-text'>

<sup>Originally posted by **qjhart** October  4, 2023</sup>
Issue #189 addressed a problem with using sources for prioritization of a work.  This comes primarily from dimensions, that can have multiple entries for a single work.  An alternative to a priority by source, we could instead score individual records.  The main think that I could think of is that you could boost a record if it has a DOI, eg.  This probably needs some input from our expert citation librarians. 

</div>

**Comment by qjhart** [comment]
I had to address this sooner rather than later, because we had works where every source was doubled.  So, I tried to break ties within doubled sources using DOIs and then I also verified that if the source had the same score, I'd [arbitrarily choose one](https://github.com/ucd-library/aggie-experts/blob/bbb2bc25244ae5689f7daa7934a609de671116a8/harvest/experts-client/lib/query/authorship/construct.rq#L124).  I also gave sources with [DOI's a big boost in scoring](https://github.com/ucd-library/aggie-experts/blob/bbb2bc25244ae5689f7daa7934a609de671116a8/harvest/experts-client/lib/query/authorship/construct.rq#L115).

**Comment by qjhart** [comment]
@Vensberg please note these changes in citation field scoring

**Comment by Vensberg** [comment]
@qjhart , to summarize, each source is scored based on how many data fields it has (title,authors, volume, issue, pages, publisher, etc) and then having a DOI gives the score an additional boost?

**Comment by qjhart** [comment]
@Vensberg, no it still uses that same ordering for every field, but if the record has a DOI, then it's ordering is scored higher, so eg even though say `figshare`  is ranked at 14, if that record had a DOI then it'd be ranked at 4 instead.  More importantly, we saw, eg *two* pubmed records for the same work, and in that case it would prefer the one with the DOI. 

Looking these scores over, though I wonder if I should do a few things :
1. Make the verified-manual even lower, so that it;s always preferred 
2. Make the boost higher.  Fig-share is a good example, they will assign DOIs for submissions, so in some since if they have the DOI, they should be used. 

Really, we might think that if there is a verified manual, then we only use that, even in the case, eg that it doesn't have a pages, but other sources do.

We might let Megan in on our strategy, and see what they think

**Comment by Vensberg** [comment]
@qjhart , so then we are following ("verified-manual" 1)("dimensions" 2)("pubmed" 3)("scopus" 4)("wos" 5)
          ("wos-lite" 6)("crossref" 7)("epmc" 8)("arxiv" 9)("orcid" 10)("dblp" 11)  ("cinii-english" 12)("repec" 13)("figshare" 14)
          (	"cinii-japanese" 15)("manual" 16)("dspace" 17) with a DOI boost?
