### ISSUE TITLE
Create login.html page similar to RC

### ISSUE THREAD

**Issue by UcDust** [ucd-library/aggie-experts#211]
Login should be required before gaining access to the site.

**Comment by qjhart** [comment]
@UcDust RC included a FLAG `IS_PRIVATE` or something similar.  Are we going to replicate that setup?

**Comment by UcDust** [comment]
@qjhart 

I haven't looked into this code too much yet, but I didn't see much about a private flag. Checking today, in the spa middleware I do see a `hiddenTypes` array in the main app_config global object, which is populated from `config.data.private.types`. However there is nothing set in the config file for it-
<img width="1728" alt="Screenshot 2023-10-16 at 10 32 27" src="https://github.com/ucd-library/aggie-experts/assets/103536473/7a67e17e-a9e6-4598-8f53-946019b3f80b">

And looking at the site, that array is empty-
<img width="1728" alt="Screenshot 2023-10-16 at 10 33 20" src="https://github.com/ucd-library/aggie-experts/assets/103536473/ebf17726-ff8a-4dbe-9d6f-e19ff7a37e81">

Does that sound like what you're referring to?
