### ISSUE TITLE
CDL elements API failure

### ISSUE THREAD

**Issue by qjhart** [ucd-library/aggie-experts#221]
Some API calls seem to fail on the server end of the elements setup.  Eg.
`http --session=elements https://oapolicy.universityofcalifornia.edu:8002/elements-secure-api/v5.5/users/15096/relationships detail==full modified-since==2019-05-01T00:27:04.357 after-id==5571651` fails, however

`http --session=elements https://oapolicy.universityofcalifornia.edu:8002/elements-secure-api/v5.5/users/15096/relationships detail==full modified-since==2019-05-01T00:27:04.357 after-id==5571651 per-page==20` succeeds 

We need to verify with Sympletic this is a problem on their end.

**Comment by rakunkel-ucd** [comment]
Both calls fail with a time-out for me. (from home)
The call succeeds with per-page=10

**Comment by rakunkel-ucd** [comment]
Was your fail also a timeout?

**Comment by qjhart** [comment]
No, I was getting a buffer length error,  but it's working now.  Let me
retry chertok from the beginning again.
