### ISSUE TITLE
CDL elements user groups

### ISSUE THREAD

**Issue by qjhart** [ucd-library/aggie-experts#225]
# CDL Groups

The senate and federation groups have been defined for [Aggie Experts](https://oapolicy.universityofcalifornia.edu/viewobject.html?cid=20&id=1576).  These are a combination of UCOP title data, and a set of rules based on CDL's CTO codes for senate (Presumably UC-wide), and the specific rules for Federation membership (from Durst)  Detailed information is available at [UCOP README](https://github.com/ucd-library/aggie-experts/tree/dev/harvest/vocabularies/experts.ucdavis.edu%252Fucop).

The groups are in the aggie-experts section of CDL.

Additionally, I reached out to the IAM team, regarding having this information included in the IAM APIs.

**Comment by qjhart** [comment]
Comparisons between title and class codes was started, back when dealing with MIV, [title codes](https://docs.google.com/spreadsheets/d/1aWsQUyS1GDzwUOjVHnb0YJ-IcpSR_22a0LGgXxu-V80/edit#gid=1904503450)  This combined a number of sources on who/what title codes should be included

**Comment by rakunkel-ucd** [comment]
I need more help to understand this issue.

**Comment by Vensberg** [comment]
@rakunkel-ucd We have a group in Elements https://oapolicy.universityofcalifornia.edu/viewobject.html?cid=20&id=1576 that is supposed to include all senate faculty. There are 1882 people in it. When my students looked at departmental pages, https://docs.google.com/spreadsheets/d/1hONWMEq3s2UeHmoTk7sIAcpyBWzmZNkif-RQ31C-Gf4/edit#gid=0, they found 2805 people. Those pages include federation faculty, so the question is, does the current group include everyone or are we missing someone. The title and class codes are supposed to help us navigate between the different employment groups for the roll-out, but the groups used in Elements don't quite correspond to the hr system codes.

**Comment by rakunkel-ucd** [comment]
Should I harvest the IAM records with isFaculty=true and create a spreadsheet for analysis?

**Comment by rakunkel-ucd** [comment]
These example IAM elements may be useful

						"titleCode": "001132",
						"titleOfficialName": "PROF EMERITUS(WOS)",
						"titleDisplayName": "PROF EMERITUS(WOS)",
						"positionTypeCode": "5",
						"positionType": "Academic",
						"percentFulltime": 0,
						"createDate": "2023-06-28 05:01:31",
						"modifyDate": "2023-06-30 05:10:23",
						"emplClass": "21",
						"emplPositionNumber": "41002705",
						"reportsToEmplID": "10238480"

**Comment by rakunkel-ucd** [comment]
There is also an IAM query for titles. Example:
		{
				"titleOId": "187A069BCE680609E040EDA991693B82",
				"titleCode": "001100",
				"titleOfficialName": "PROF-AY",
				"titleDisplayName": "PROF-AY",
				"createDate": "2006-07-13 12:51:14",
				"modifyDate": "2023-10-24 15:46:58"
			},

**Comment by qjhart** [comment]
@Vensberg Although it's not super organized, I hope you did spend the time to review the work that I did previously to match the title codes to the senate and federation.  This is the [title code](https://docs.google.com/spreadsheets/d/1aWsQUyS1GDzwUOjVHnb0YJ-IcpSR_22a0LGgXxu-V80/edit?usp=sharing) link above.

**Comment by qjhart** [comment]
@Vensberg  / @rakunkel-ucd  close when reviewed
