### ISSUE TITLE
Adding for developer testing

### ISSUE THREAD

**Issue by qjhart** [ucd-library/aggie-experts#241]
## Adding Experts for Development testing
These are some developer notes on testing particular experts for Aggie Experts

## Solution / Notes
Currently, developers typically get a small set of experts included in their testing setup.  The methodology for this is that there is a pre-defined GCS bucket containing a small number of experts.  On initialization, the contents of this bucket is added to the system. 

One can see the configuration parameter with `bin/aggie-experts config`.  The buckets are available for viewing via the google cloud console, or via tools like:

```bash
gsutil ls gs://aggie-experts-fcrepo-dev/expert
```

### Fetching a single expert

In the aggie expert filesystem,  an Experts' relationships to citations, and grants, are stored within the directory of the expert themselves.  This means that a developer can get all items relevant for a user via one directory.  For example, you can use `gsutil` to get a single user (like say Jonathan Eisen, 226d2dccfba4c2be04aedd4f9f942e42) .  You can get that from any other bucket as well.  For example. the command below gets eisen's data from the sandbox bucket.

``` bash
d=test
mkdir ${d}
gsutil -m rsync -r -x '(?!expert/226d2dccfba4c2be04aedd4f9f942e42.*)' gs://aggie-experts-fcrepo-sandbox ${d}
```

The `-x '(?!expert/226d2dccfba4c2be04aedd4f9f942e42.*)' ` parameter excludes everything that isn't part of eisen's record.

### Adding with fin

After fetching your data, you can easily add it to your development for testing using `fin`

```
fin config set host http://localhost
fin auth login
fin io import --import-from-root --fcrepo-path-type=subpath --log-to-disk ${d}
```

You can watch the import fire events in the 'http://localhost/fin/admin/' dashboard.  This is an example the above import

![image](https://github.com/ucd-library/aggie-experts/assets/344953/b29666f5-1cb2-4369-8e9f-759e3a6473e3)

**Comment by qjhart** [comment]
@rakunkel-ucd @UcDust Please review, and if it it looks good, then remove yourselves from the issue.

**Comment by UcDust** [comment]
@qjhart 

Thanks, this worked perfectly! 

I assume if we leave off the `-x` param in the gsutil export step, it would include everything? Any risk there?

**Comment by qjhart** [comment]
@UcDust - No risk at all! You could also add 5 users into the same test directory.  You could also remove all but a few relationships, or alter the data if you wanted to try some weird testing.

Also, if you do sync the whole sandbox over, `fin` will check and only import changes if you try to import the whole set mulitple times.
