### ISSUE TITLE
Not all relationships are included for a grant

### ISSUE THREAD

**Issue by qjhart** [ucd-library/aggie-experts#273]
**Describe the Issue**
Not all the grant relationships are represented for a particular grant.   The issue in this case is that we are currently getting the roles for the grants, but unlike publications, we need to have a field to show additional roles.

The way we will accomplish this is to create a text field for the grant, which shows all the PIs and Co-PIS as names only.  We can then parse this field alone when we are fetching grants.  

This allows us to shows these person names without having to extract every role from the CDL system.

**Expected behavior**
Any grant can show the names of all the PIs and CO-PIs, regardless of whether they are an expert, or even in any system, IAM and/or CDL.

**QA / QC**
@Vensberg will review the data after it's been completed.

## Solution

#299 added the role names to the grants.hdt file, and the explanation there shows how to use this to create the new role.

**Comment by qjhart** [comment]
@rakunkel-ucd , I have updated the issue above, based on our TH meeting, and I have documented in the PR #299 how the change to the roles, can be used to include these names.

**Comment by Vensberg** [comment]
@UcDust, Roles look good. I updated the list of fields for download in https://github.com/ucd-library/aggie-experts/issues/55 based on a discussion with @qjhart (that's the last item on the list)
- [x] UI shows title, year range, role, agency
- [x] Download includes role
- [ ] Please, replace List of Contributors with List of PIs and coPIs {separate contributors by ";"} |

**Comment by Vensberg** [comment]
@UcDust , I still see question marks in the Contributors column of the spreadsheet download of grants.
