### ISSUE TITLE
Manage My Grants Admin download

### ISSUE THREAD

**Issue by UcDust** [ucd-library/aggie-experts#289]

**Comment by UcDust** [comment]
@Vensberg this should be ready to test once the code has been deployed.

**Comment by Vensberg** [comment]
@UcDust , I still see question marks in the Contributors column of the spreadsheet download of grants.

**Comment by Vensberg** [comment]
Also, some of the grants do not have a Type.

**Comment by UcDust** [comment]
@Vensberg were you testing this on sandbox?

**Comment by Vensberg** [comment]
@UcDust , I realized what happens: grant download happens in two ways: from the main profile page, to download all grants. That works.
Then, when clicking on "manage grants", there is another opportunity to download grants one by one (or page by page). This one has not been updated.
