### ISSUE TITLE
Document Supported Grant Roles

### ISSUE THREAD

**Issue by qjhart** [ucd-library/aggie-experts#307]
There are grant roles as defined in CDL, KFS, VIVO, and AggieEnterprise.  We need to define the set of roles we support and the crosswalk between them.

The [spreadsheet](https://docs.google.com/spreadsheets/d/1OmbbL0RETOv8xpRCQVcWqzA1iaSU-6KVvXMZDvAAyCs/edit?usp=sharing) shows the various sets of relationships.

We either need to decide to use VIVO, or extend VIVO with our own definitions, and map all the other relations to this set.

**Expected behavior**
Different Grant relationships will be mapped to these

**QA / QC**
@qjhart will review

**Comment by Vensberg** [comment]
It seems to me that VIVO is sufficient. A Project Manager will be AdminRole. 
We should retain Key Personnel in AE, for archived grants, and any potential future expansion.
