### ISSUE TITLE
Create troubleshooting tips section for works/grants update issues

### ISSUE THREAD

**Issue by UcDust** [ucd-library/aggie-experts#328]
In the event of works/grants failing to update visibility in cdl, we're thinking of displaying an alert such as this:

<img width="661" alt="Screenshot 2024-02-13 at 09 01 16" src="https://github.com/ucd-library/aggie-experts/assets/103536473/e2f09ae4-44b1-4fd1-a1bc-fef4f58b074e">

Create brief documentation we can add to the FAQ page that _troubleshooting tips_ will link to.

**Comment by qjhart** [comment]
In the Error I would say something like : 

*Title of Work* changes could not be propagated to  [UC Publication Management] system.  Changes may not be persistent when your data is resynced.  You can make changes directly in the [UC Publication Management] system. 

Then the troubleshooting tips:

Aggie Experts uses the [UC Publication Management] system as it's official record of an expert's citation.  When an experts makes and editorial change, like changing the visibility or rejecting a citation, this action is first performed on the local Aggie Experts data.  Then, using a proxy we attempt to make the same edit for the expert in the Management system.  If that system is not available that process might fail.  In this case, the expert's selection may be reverted when the next sync with this system takes place.  Experts can make their desired changes directly in the [UC Publication Management] application, and these changes will be reflected on the next synchronization with that database.

[UC Publication Management]:https://oapolicy.universityofcalifornia.edu/

**Comment by qjhart** [comment]
@Vensberg Please review, and assign back to @UcDust when complete.

**Comment by qjhart** [comment]
@UcDust how do you want to get this information back on the client?  How about a 502  or 504 Error for this and a 500 error for internal issues, and then response with json as a list of components, so a successful fix, but unsuccessful propagation woulc look like:

```json
[
{"id":"index","code":200},
{"id":"fcrepo","code":200},
{"id":"cdl","code":504,"error":"Server Timeout"}
]
```

or 
```json
[
{"id":"index","code":200},
{"id":"fcrepo","code":200},
{"id":"cdl","code":502,"error":"Invalid token, eg"}
]
```

**Comment by Vensberg** [comment]
@qjhart Is this for visibility only or for reject as well?

**Comment by UcDust** [comment]
@qjhart that structure with the response codes for each service sounds good.

**Comment by Vensberg** [comment]
@UcDust , @qjhart 

Visibility:
Changes to the visibility of (Title of Work) could not be done through Aggie Experts right now. Please, try again later, or make changes directly in the [UC Publication Management System](). <--I'd like this URL to take them directly to the Claimed page https://oapolicy.universityofcalifornia.edu/listobjects.html?as=1&am=false&cid=1&tids=5&ipr=true
Note that the URL will need to change for grants to land on the grant page. Do you want to use the QA URL as a placeholder? (https://qa-oapolicy.universityofcalifornia.edu/listobjects.html?as=1&am=false&cid=2&oa=&tol=&tids=&f=&rp=&vs=&nad=&rs=&efa=&sid=&y=&ipr=true&jda=&iqf=&id=&wt=)


Then the troubleshooting tips:

On the FAQ page, section Managing Your Profile, question How do I change the visibility of a publication or a grant?, add a troubleshooting tag.

Troubleshooting
Aggie Experts uses the [UC Publication Management System](https://oapolicy.universityofcalifornia.edu/) system as it's official record of an expert's citation. When an experts makes an editorial change, like changing the visibility or rejecting a citation, this action is first performed on the data you see in Aggie Experts, and then propagated to the Publication Management System. If that system is not available, the process might fail, and you will see an error message. In this case, the expert's selection may be reverted when the next sync with this system takes place. You can make the desired changes directly in the [UC Publication Management]( https://qa-oapolicy.universityofcalifornia.edu/listobjects.html?as=1&am=false&cid=1&tids=5&ipr=true) application, and these changes will be reflected on the next synchronization.

Then, create a new question in the same section: "How do I reject a publication?"

Click on the edit icon above the list of your works. Once the "Manage My Works" page opens, click on the trash can icon by the publication that you want to disclaim.

Troubleshooting
Aggie Experts uses the [UC Publication Management System](https://oapolicy.universityofcalifornia.edu/) system as it's official record of an expert's citation. When an experts makes an editorial change, like changing the visibility or rejecting a citation, this action is first performed on the data you see in Aggie Experts, and then propagated to the Publication Management System. If that system is not available, the process might fail, and you will see an error message. In this case, the expert's selection may be reverted when the next sync with this system takes place. You can make the desired changes directly in the [UC Publication Management]( https://qa-oapolicy.universityofcalifornia.edu/listobjects.html?as=1&am=false&cid=1&tids=5&ipr=true) application, and these changes will be reflected on the next synchronization.

**Comment by Vensberg** [comment]
The Reject message would be:
Rejecting (Title of Work) could not be done through Aggie Experts right now. Please, try again later, or make changes directly in the [UC Publication Management System](https://github.com/ucd-library/aggie-experts/issues/328).

For more help see troubleshooting tips. 

redirects to the FAQ above.

**Comment by UcDust** [comment]
@Vensberg @qjhart 

Does this look good to you for the FAQ sections?

<img width="1057" alt="Screenshot 2024-02-14 at 09 15 59" src="https://github.com/ucd-library/aggie-experts/assets/103536473/239bc998-a0cd-47e0-b5f8-1a4428c49904">

**Comment by Vensberg** [comment]
I had some errors in the text. Here's the corrected version.
![FAQ_edits](https://github.com/ucd-library/aggie-experts/assets/26015534/a94cb76b-2b47-4d96-b191-e8cf71fb20cc)
