### ISSUE TITLE
Are grants no longer associated with any expert still discoverable

### ISSUE THREAD

**Issue by qjhart** [ucd-library/aggie-experts#335]
**Description:**
Under normal circumstances, CDL Elements does not allow grants that have no link with any current member.  In our current archive, there are about 5K such grants, that no longer have anyone at UC Davis associated with them.  As a user of Aggie Experts do I want to discover grants that are no longer linked to a user? 

The more simple solution is to leave these out of Aggie Experts.  We could test the system to verify that any unaffiliated grants (like removing some users) would also get removed.  Because we typically have only the title and funding agency saved to CDL, there isn't a lot of interesting data we get from keeping it. 

The only thing is that we *could* actually include the administrative department that managed the grants.  These departments could then get a more complete record of the grants they have received in the past. 

If we wanted to keep them, we could assign these grants to the `aggie-experts` user (as an administrator) This would be enough to keep them in the system and discoverable.  We would have to also decide then if we want to include the department.
  
**Acceptance criteria:**
@Vensberg gives us some direction on how to proceed.

\

**Comment by qjhart** [comment]
@rakunkel-ucd will delete the relationship relating to this [grant](https://qa-oapolicy.universityofcalifornia.edu/viewobject.html?id=4432655&cid=2) and we'll test for the existance of the grant in CDL.

**Comment by rakunkel-ucd** [comment]
The content of links_deletions.csv for this test is:
category-1,id-1,category-2,id-2,link-type-id
"user","10206969","grant","ark:/87287/d7gt0q/grant/K384228-101552","120"

**Comment by rakunkel-ucd** [comment]
KFS archived grants have been re-imported to QA Elements successfully using this scheme. Any KFS grant that does not have a PI that matches a Elements user is linked to the user "_Aggie Experts". This is done by including a row in the links.csv upload to establish  the relationship. Review user "_Aggie Experts" to see the list of these grants.

**Comment by Vensberg** [comment]
- [x] Search for AGGIE EXPERTS, _ user with no institution selected returns 4603 grants.
