### ISSUE TITLE
Grant visibility testing

### ISSUE THREAD

**Issue by UcDust** [ucd-library/aggie-experts#336]
Tests for hiding/showing grants.

Test for scenario when Aggie Experts cannot connect to Elements to change the visibility of a grant.

**Comment by UcDust** [comment]
The API code essentially updates grant visibility in these stages:

1. Updates the visibility in elasticsearch
2. Updates the visibility in fcrepo
3. Updates the visibility in cdl

For development, we'll need to make sure a 500 error in step 1 doesn't change the visibility in the ui (this might be hard to replicate on test, but we can replicate locally, or deploy an update to sandbox with some intentionally failing code). 
A 500 error for step 2 and 3 should still update visibility in the ui for what elasticsearch has been updated to.

**Comment by Vensberg** [comment]
@UcDust , 
On changing the visibility of a grant, I see the message

Error: Update Failed

Changes to the visibility of (Travel Support for Participants in the 2015 New Security Paradigms Workshop) could not be done through Aggie Experts right now. Please, try again later, or make changes directly in the [UC Publication Management System.](https://qa-oapolicy.universityofcalifornia.edu/listobjects.html?as=1&am=false&cid=2&oa=&tol=&tids=&f=&rp=&vs=&nad=&rs=&efa=&sid=&y=&ipr=true&jda=&iqf=&id=&wt=)

For more help, see [troubleshooting tips.](https://test.experts.library.ucdavis.edu/faq#visible-publication)

- [ x] The error message appears--good
- [x ] UC Publication Management System redirects to Elements QA claimed grants as per requirement --good
- [ ] Even though the FAQ redirects to what should be a bookmarked answer, the page opens at the very top of FAQ. Can the "How do I change the visibility of a publication or a grant?" be opened as the user lands on that page?
- [ ] @Vensberg , re-check this when test is updated: When I click OK, the page looks fine, but when I refresh, the visibility icon is crossed out. We need to discuss tomorrow at sprint what should happen there--we had discussed the option of "hide from the interface now, we'll propagate to Elements later"

**Comment by Vensberg** [comment]
Good on sandbox. Will check again when is moved to test.

**Comment by UcDust** [comment]
@Vensberg this should be ready to test once the code has been deployed.

**Comment by Vensberg** [comment]
I checked one of John Madigan's grants. On the second try it worked as expected, with a time wheel while the visibility changed. The relationship on QA also changed as expected.
The grants are hidden from search as well.
The number of hidden grants is correctly reflected as well.
Looks great!

**Comment by Vensberg** [comment]
- [ ] Keeping hte issue open to retest on test

**Comment by Vensberg** [comment]
The timing out happens a bit too fast.

**Comment by UcDust** [comment]
@Vensberg can you explain what you mean about the timing out issue?

**Comment by Vensberg** [comment]
Works in production.
