### ISSUE TITLE
Elements Visibility flag needs to be reflected in Aggie Experts

### ISSUE THREAD

**Issue by Vensberg** [ucd-library/aggie-experts#343]
**Describe the bug**
When users in Elements set their profile visibility to internal, they should not appear in Aggie Experts. 
The IAM visibility flag needs to be tested as well.

**Expected behavior**
Once the Elements profile is set to internal, no data about the user, including name, appears in Aggie Experts.

**Comment by qjhart** [comment]
@Vensberg, I'm reviewing the Directory listing component for hiding users, and I am seeing that the `privacyCode` doesn't seem to be working as I expected.  It doesn't seem to affect users' being in the directory.  

I will add the change for CDL, but the IAM portion will be blocked, till we hear back.

I sent this note off:
> If you go to [odr.ucdavis.edu](http://odr.ucdavis.edu/), then you have the opportunity to select/de-select the *Publish LIsting* in  the upper right, and this immediately affects the [directory.ucdavis.edu](http://directory.ucdavis.edu/) search.  However, if you use the profiles API, eg: 
> http https://iet-ws.ucdavis.edu/api/iam/people/profile/search Content-Type:application/json key==${key} v==1.0 email==qjhart@ucdavis.edu
> I can't see where this is represented.  I had thought that this was the flag in the top section of this 'privacyCode`, but I see  users with this not null still come up in the directory search.  
> Can you let me know where this is represented in the profile API?

**Comment by Vensberg** [comment]
Checked for a user with an internal Elements flag, and the user is not in sandbox. Great!

**Comment by Vensberg** [comment]
- [ ] Keeping the issue open to retest on test
