### ISSUE TITLE
Faculty  Data issues

### ISSUE THREAD

**Issue by qjhart** [ucd-library/aggie-experts#351]
**Describe the bug**
There are a few data issues that need to be tracked down:

- [ ] Why does Joann Emerson have two names
- [ ] Why does Thomas Moore have multiple titles?
- [ ] Why did we lose these persons on last update? https://github.com/ucd-library/aggie_enterprise_kfs_grant_archive/pull/2/files

-[ ] https://github.com/ucd-library/aggie-experts/pull/365

**Comment by Vensberg** [comment]
@Vensberg , keep track of data issues here

**Comment by Vensberg** [comment]
- [ ] expert/c03c312163631a80b53c68292d9881bf not showing Roles

**Comment by Vensberg** [comment]
- [ ] Duplicated article https://test.experts.library.ucdavis.edu/works/expert/bebbd7ca5b2309e3446ab7f381347fd1; Editorial
journal article . Strong, D., & Whelan, A. M. Ecology, 96(1), 1–2. https://doi.org/10.1890/0012-9658-96.1.1
Host selection by an insect herbivore with spatially variable density dependence
journal article . Wetzel, W. C., & Strong, D. R. Oecologia, 179(3), 777–784. https://doi.org/10.1007/s00442-015-3378-3

**Comment by Vensberg** [comment]
In the Browse setup, letter M
Ma, Jeffrey appears without a title under the name. I don't see this issue with other names in the Browse.

**Comment by Vensberg** [comment]
Nancy Lane is not is the system. I added her to the additional members, but it would be good to understand why she was missing from the senate group.

**Comment by Vensberg** [comment]
Expert MIUGNZIx is a faculty in 2 departments, but one of them gets rendered twice; everything is the same, including the email. RGPO/UCD group.

**Comment by Vensberg** [comment]
Expert LKAD95pM doesn't have their publications imported.

**Comment by Vensberg** [comment]
Missing publications here pjGhrpxb

**Comment by Vensberg** [comment]
Expert /Qn8V0Aj5 is listed as a researcher on his profile for this grant UC DAVIS CLINICAL AND TRANSLATIONAL SCIENCE CENTER, 2021-2026, but he is the PI according to Elements. The grant landing page correctly identifies him as the PI, so the only issue is how the data gets translated to the profile.

**Comment by qjhart** [comment]
@Vensberg let's make them seperate issues now that they are more particular

**Comment by Vensberg** [comment]
Publications 1486102 and 1454109 appear identical

**Comment by Vensberg** [comment]
This article's landing page https://experts.ucdavis.edu/work/ark:/87287/d7mh2m/publication/2701580 won't load. Note the doubling title. The Thoracic Surgery Social Media Network: Early experience and lessons learned,The Thoracic Surgery Social Media Network: Early Experience and Lessons Learned

**Comment by Vensberg** [comment]
Publication work/ark:/87287/d7mh2m/publication/4725228 has first author as undefined.

**Comment by Vensberg** [comment]
This person has their CTO code showing along with their title https://experts.ucdavis.edu/expert/gjkyWQsi

**Comment by qjhart** [comment]
> This person has their CTO code showing along with their title https://experts.ucdavis.edu/expert/gjkyWQsi

This is a problem in that that's how the "Official" Department Name is for that department :(.  This should be changed at the IAM level.  It's the same for everyone in that department w/out an ODR entry: 

https://experts.ucdavis.edu/search?q=BIOLOGICAL%20%2526%20AG%20ENGINEERING&@type=expert
