### ISSUE TITLE
AE--Elements connection glitch

### ISSUE THREAD

**Issue by Vensberg** [ucd-library/aggie-experts#364]
**Describe the bug**
I can make changes on the visibility and reject works on the AE interface, but nothing happens in Elements. Yesterday, during testing users got error messages when trying to reject, so I was trying to reproduce that today, but I saw this new behavior.

**To Reproduce**
1. Go to [Quinn's profile](https://test.experts.library.ucdavis.edu/works-edit/expert/66356b7eec24c51f01e757af2b27ebb8)
2. In the section for 2014 there were two publications.
I rejected Design of a GIS-based web application for simulating biofuel feedstock yields, and it disappeared from AE, but in [Elements](https://oapolicy.universityofcalifornia.edu/viewobject.html?cid=1&id=2713711) it is still claimed
I changed the visibility of Modeling Poplar Growth as a Short Rotation Woody Crop for Biofuels, but in [Elements](https://oapolicy.universityofcalifornia.edu/viewobject.html?cid=1&id=2449942) the relationship is still public

**Expected behavior**
Elements should reflect the changes in AE, or an error message should appear (both were previously in place)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version 123.0.1

**Comment by UcDust** [comment]
@Vensberg this should be addressed now. Could you let us know if you still see any issues?

**Comment by Vensberg** [comment]
Looks good.
