### ISSUE TITLE
Some Aggie Enterprise Grant Fail to Import

### ISSUE THREAD

**Issue by rakunkel-ucd** [ucd-library/aggie-experts#367]
There are cases of aggie-enterprise grants with no user cdl link. So 44 of the batch don't import.

**Comment by rakunkel-ucd** [comment]
[Import_Errors_2024-03-07_(15_00).txt](https://github.com/ucd-library/aggie-experts/files/14563450/Import_Errors_2024-03-07_.15_00.txt)

**Comment by qjhart** [comment]
@Vensberg these are a weird set up instances.  As far as we can tell, these grants are all ones where the PI is in Berkeley or somewhere, and the only link to UC Davis is via an admin role. So we aren't too concerned if they aren't included.
