### ISSUE TITLE
Investigate non-resolvable links in Aggie Experts from ODR/Elements

### ISSUE THREAD

**Issue by UcDust** [ucd-library/aggie-experts#381]
We need a list of all URLs that go on the About Me section, the name of the expert, whether the link resolves or not, and whether it comes from ODR or Elements.

This will power an effort to move all resolvable URLs (and fixed broken ones) into Elements, so that we can update them timely.

**Comment by UcDust** [comment]
Chatting with @Vensberg this morning, this came from her conversation with @qjhart yesterday:

`What we actually landed on is a list of all URLs that go on the About Me section, the name of the expert, whether the link resolves or not, and whether it comes from ODR or Elements.`.

**Comment by UcDust** [comment]
Here's a [list of urls](https://docs.google.com/spreadsheets/d/1E5oLd93NS8K20ha_V2QN_a-v8dqGivLWTh7_GIVNtRU/edit#gid=1712295818) checked. 

A `status` other than 0 is a failure.

**Comment by Vensberg** [comment]
We moved working links to Elements and deprecated ODR as a source for those.
