### ISSUE TITLE
Regular users can't see other pages

### ISSUE THREAD

**Issue by Vensberg** [ucd-library/aggie-experts#385]
**Describe the bug**

A user is able to log in and see their profile, but not the profile of other users. I as an admin had a similar issue, but it self resolved. Regular users continue to have it. They then search and see results. Clicking on 

**To Reproduce**
1. Log in as a regular user.
2. Reach your profile
3. Search
4. Click on another person in the results 
5. See a 404 page

**Comment by UcDust** [comment]
@Vensberg this should be ready for review on test.
