### ISSUE TITLE
Users can download their citations in RIS file format that has only one date listed as the official publication date.

### ISSUE THREAD

**Issue by Vensberg** [ucd-library/aggie-experts#39]
The date in the citation is the official date of publication. MIV can only import one date, so this is necessary to ensure proper publication metadata transfer to MIV.

Priority: H
Value: H
Risk: L
Effort: L

---
- [x] #31
- [ ] ...

**Comment by qjhart** [comment]
@Vensberg can you explain how to test/verify this?

**Comment by Vensberg** [comment]
I import the file into their sandbox and see if any imports fail and any errors are returned.
