### ISSUE TITLE
Remove Search Match Summary

### ISSUE THREAD

**Issue by qjhart** [ucd-library/aggie-experts#390]
On searches, each user has a tag-line of matching search results.  This needs to be hidden.  Will return when we can point to a search page showing these items:

![image](https://github.com/ucd-library/aggie-experts/assets/344953/96ea1892-5893-4efb-a3f2-cfd32069ded6)

**Comment by UcDust** [comment]
@Vensberg this should be ready for review on test.

**Comment by Vensberg** [comment]
@UcDust , looks good; the match counts are gone.
