### ISSUE TITLE
UI regexp for Grant Titles

### ISSUE THREAD

**Issue by qjhart** [ucd-library/aggie-experts#394]
Users don't like to see the grant identification number in the title of the grant. These were added when grants were moved from KFS, but we are unsure if they are in grants that we developed in the new system

- [ ] Find out if all titles have these identifiers at the end @rakunkel-ucd 
- [ ] Add a `replace()` to remove them from the titles in the UI? or the grant information page?  @qjhart @UcDust

**Comment by UcDust** [comment]
@qjhart @rakunkel-ucd 
For the regex replace in item 2 of the description, are they essentially like `K322D09`? Also, what's the pattern that we need to match exactly, like K followed by 3 random digits followed by D followed by 2 random digits?

**Comment by Vensberg** [comment]
@UcDust , it matches the grant ARK qualifier.

**Comment by UcDust** [comment]
@qjhart 
I've done a `replace()` for grant titles when generating the grants to render in the ui. I've tagged this issue in that commit. This affects all grant ui pages, and the grant download. 
Let me know if you'd like to try a different approach instead.

**Comment by Vensberg** [comment]
Looks good in the new data pull.
