### ISSUE TITLE
Pager component should always show the last page using ellipses

### ISSUE THREAD

**Issue by UcDust** [ucd-library/aggie-experts#396]
Pager appears to not be implemented correctly – pager should always show the last page using the ellipses attribute when max page count exceeds visible count so that people understand how deep the content goes and can quickly access that content.
Example: [Junyi Qi](https://test.experts.library.ucdavis.edu/works/expert/6c7c5bd5d7effc0c58a885309ec868d1) shows 7 pages of works on load, but once you start clicking there are actually 11 pages of content.
Pager Component: https://brand.library.ucdavis.edu/#ucd-theme-pagination 

Should show  1 2 3 4 5 6 … 11

**Comment by UcDust** [comment]
@Vensberg this should be ready for review on test.

**Comment by Vensberg** [comment]
@UcDust , when I click on the ellipses, the page numbers disappear. There are only left and right arrows. I am still on the original page. The arrows reload the same page.
It's probably a good idea to let the rest of the team know--the library website gives a 404 when you click on the ellipses.

I don't see guidance on what the ellipse is supposed to do. In GeeksforGeeks it moves the user half-way across the pages.

**Comment by UcDust** [comment]
This should be patched in [this PR](https://github.com/ucd-library/ucdlib-theme/pull/92)
