### ISSUE TITLE
User profile loads with empty content when returned from another page

### ISSUE THREAD

**Issue by UcDust** [ucd-library/aggie-experts#397]
One user’s profile loaded as empty when they returned to it from another page. We had to ask them to refresh the page to make it reappear.

Go to My Profile -> Search (climate) -> pick someone -> back arrow -> back arrow.  Page is not refreshed

**Comment by Vensberg** [comment]
Works for me, too, now. I'll need to add this to the next round of testing to watch if it comes back. I'm tagging myself here and putting this issue in QA.
