### ISSUE TITLE
AE - investigate missing grant types, and PI/coPI duplication

### ISSUE THREAD

**Issue by qjhart** [ucd-library/aggie-experts#398]
As an example, download the grants for [this expert](https://test.experts.library.ucdavis.edu/expert/8cdcb575bc6553d3f912e76f1f5c484e).

Many are missing the type because the ui is using `http://www.w3.org/1999/02/22-rdf-syntax-ns#type`. 

After chatting earlier, it's possible we need to use rdfs instead of rdf types, and the type could be added to the `@type` array.

**Comment by qjhart** [comment]
hey there, so I had created a placeholder for the grant types in https://github.com/orgs/ucd-library/projects/24/views/5?pane=issue&itemId=57006823. I think the first part you said you were going to change the rdf type to rdfs, and include the type in the @types array instead of using the rdf uri. is that right, and is that anywhere that I can test? the second part of that task is the PI/coPI duplicating in the grants download file. I had a question that I don't think was answered, see this screenshot from the 19th-



![Image](https://github.com/ucd-library/aggie-experts/assets/344953/04f551c1-6282-4c32-9436-221a25d449fa)

**Comment by qjhart** [comment]
I can't actually imagine when a PI will not have both the PI and the CO-PI, status.  If there are, we should put an example in here. 

The reasons were discussed with VE, re. to putting the data into CDL, and how we do that.

So, Let's look at grant in CDL.

![Image](https://github.com/ucd-library/aggie-experts/assets/344953/5950215f-5283-448f-8058-4bcbeec0da95)

You will note that the grant itself, has a Principal Investigator, the grant also has a list of Co-PIs, and finally, the grants has a number of relationships linking this grant to CDL users. 

![Image](https://github.com/ucd-library/aggie-experts/assets/344953/100c1c9c-2c48-4f37-bf31-375ff6ddad1e)

These are 3 separate things, but when the are mapped to (my) grant entry it looks like this: 

```json
{
"assignedBy": {},
"dateTimeInterval": {},
"@type": [
"vivo:Grant",
"Grant"
],
"name": "NEAR REAL TIME SCIENCE PROCESSING ALGORITHM FOR LIVE FUEL MOISTURE CONTENT FOR THE MODIS DIRECT READOUT SYSTEM",
"@id": "ark:/87287/d7mh2m/grant/4431398",
"relatedBy": [
{
"inheres_in": "expert/66356b7eec24c51f01e757af2b27ebb8",
"relates": [
"ark:/87287/d7mh2m/grant/4431398",
"expert/66356b7eec24c51f01e757af2b27ebb8"
],
"@type": [
"GrantRole",
"CoPrincipalInvestigatorRole"
],
"@id": "ark:/87287/d7mh2m/relationship/13749424",
"is-visible": true
},
{
"relates": [
{
"@type": "vivo:Person",
"name": "HART, QUINN J",
"@id": "ark:/87287/d7mh2m/grant/4431398#co_pi_b66911c899cd3447cee58cf14392df0a"
},
"ark:/87287/d7mh2m/grant/4431398"
],
"@type": "CoPrincipalInvestigatorRole",
"@id": "ark:/87287/d7mh2m/grant/4431398#co_pi_role_b66911c899cd3447cee58cf14392df0a"
},
{
"relates": [
{
"@type": "vivo:Person",
"name": "USTIN, SUSAN L",
"@id": "ark:/87287/d7mh2m/grant/4431398#pi"
},
"ark:/87287/d7mh2m/grant/4431398"
],
"@type": "PrincipalInvestigatorRole",
"@id": "ark:/87287/d7mh2m/grant/4431398#pi_role"
},
{
"relates": [
{
"@type": "vivo:Person",
"name": "KOLTUNOV, ALEXANDER",
"@id": "ark:/87287/d7mh2m/grant/4431398#co_pi_586b332a4702f921115e6560a936b4b5"
},
"ark:/87287/d7mh2m/grant/4431398"
],
"@type": "CoPrincipalInvestigatorRole",
"@id": "ark:/87287/d7mh2m/grant/4431398#co_pi_role_586b332a4702f921115e6560a936b4b5"
}
],
"sponsorAwardId": "NNX11AF93G",
"http://www.w3.org/1999/02/22-rdf-syntax-ns#type": {
"name": "Research",
"@id": "ucdlib:Grant_Research"
}
```

**Comment by qjhart** [comment]
```json
{
"assignedBy": {},
"dateTimeInterval": {},
"@type": [
"vivo:Grant",
"Grant"
],
"name": "NEAR REAL TIME SCIENCE PROCESSING ALGORITHM FOR LIVE FUEL MOISTURE CONTENT FOR THE MODIS DIRECT READOUT SYSTEM",
"@id": "ark:/87287/d7mh2m/grant/4431398",
"relatedBy": [
{
"inheres_in": "expert/66356b7eec24c51f01e757af2b27ebb8",
"relates": [
"ark:/87287/d7mh2m/grant/4431398",
"expert/66356b7eec24c51f01e757af2b27ebb8"
],
"@type": [
"GrantRole",
"CoPrincipalInvestigatorRole"
],
"@id": "ark:/87287/d7mh2m/relationship/13749424",
"is-visible": true
},
{
"relates": [
{
"@type": "vivo:Person",
"name": "HART, QUINN J",
"@id": "ark:/87287/d7mh2m/grant/4431398#co_pi_b66911c899cd3447cee58cf14392df0a"
},
"ark:/87287/d7mh2m/grant/4431398"
],
"@type": "CoPrincipalInvestigatorRole",
"@id": "ark:/87287/d7mh2m/grant/4431398#co_pi_role_b66911c899cd3447cee58cf14392df0a"
},
{
"relates": [
{
"@type": "vivo:Person",
"name": "USTIN, SUSAN L",
"@id": "ark:/87287/d7mh2m/grant/4431398#pi"
},
"ark:/87287/d7mh2m/grant/4431398"
],
"@type": "PrincipalInvestigatorRole",
"@id": "ark:/87287/d7mh2m/grant/4431398#pi_role"
},
{
"relates": [
{
"@type": "vivo:Person",
"name": "KOLTUNOV, ALEXANDER",
"@id": "ark:/87287/d7mh2m/grant/4431398#co_pi_586b332a4702f921115e6560a936b4b5"
},
"ark:/87287/d7mh2m/grant/4431398"
],
"@type": "CoPrincipalInvestigatorRole",
"@id": "ark:/87287/d7mh2m/grant/4431398#co_pi_role_586b332a4702f921115e6560a936b4b5"
}
],
"sponsorAwardId": "NNX11AF93G",
"http://www.w3.org/1999/02/22-rdf-syntax-ns#type": {
"name": "Research",
"@id": "ucdlib:Grant_Research"
}
```

So, Susan shows up both as the PI ,and as part of the Co-PIs?

**Comment by Vensberg** [comment]
@UcDust , what I am seeing is that in many cases, but not all, when the user is the PI, his name doesn't appear in the column of coPIs. Those are the same grants where the name was appearing twice in the previous version.

**Comment by Vensberg** [comment]
@UcDust I just realized that the Grant type is getting downloaded as "Grant", not as "research", "education", etc

**Comment by UcDust** [comment]
@Vensberg I just looked over the data in _test_ vs _experts_, and it looks like these issues should be fixed now in _experts_ with the new schema changes. Specifically the grant _type_ in the download and the list of _coPI_s. Let me know if you notice any issues in _experts_ though.

**Comment by Vensberg** [comment]
@UcDust , all the  data in the CSV looks good. Could you change the last column to "List of PIs and CoPIs"? We had users find it confusing to that they are included in the coPI list when they are PIs. We want that column to be a constant list of PIs+coPIs, as it is now, so this is just a question of renaming the column for clarity.
