### ISSUE TITLE
Understanding citation changes

### ISSUE THREAD

**Issue by Vensberg** [ucd-library/aggie-experts#413]
Quinn noticed that the data errors went from 800->200. Can we get a report of the old errors and the new errors to follow up on the changes?

**Comment by UcDust** [comment]
[validation-errors.csv](https://github.com/ucd-library/aggie-experts/files/14963160/validation-errors.csv)

@Vensberg 
Here's a document that shows the error list, and whether the error shows up on stage, test, or both stage and test. Would this work for you?

**Comment by Vensberg** [comment]
@UcDust , perfect.
