### ISSUE TITLE
Add event tracking for work/grant downloads in GA4

### ISSUE THREAD

**Issue by UcDust** [ucd-library/aggie-experts#420]

**Comment by UcDust** [comment]
[This PR](https://github.com/ucd-library/aggie-experts/pull/421) should address this issue.

**Comment by UcDust** [comment]
<img width="1373" alt="Screenshot 2024-04-17 at 11 56 25" src="https://github.com/ucd-library/aggie-experts/assets/103536473/cbe6059e-e7b3-41ce-ba6a-2d2b9fa86496">

@Vensberg 
Here's an example of the _grants download_ and _works download_ events. I've wired it in on the expert page and on the edit pages of grants/works. You can view the events in GA from the `Reports > Engagement > Events` page. They show up about 24 hours after being triggered.

**Comment by Vensberg** [comment]
@UcDust , looks great.
