### ISSUE TITLE
Update expert ui/api to show unlabeled websites from elements

### ISSUE THREAD

**Issue by UcDust** [ucd-library/aggie-experts#427]

**Comment by qjhart** [comment]
@UcDust this PR #428 adds these unlabeled websites to the expert record

**Comment by UcDust** [comment]
<img width="1435" alt="Screenshot 2024-04-17 at 11 35 26" src="https://github.com/ucd-library/aggie-experts/assets/103536473/68ce3d62-b50a-4291-ad61-28caea8e3be8">

Here's an example of some links from Quinn.

**Comment by UcDust** [comment]
@wrenaria 

Could you weigh in on the display of longer links? @Vensberg had mentioned in slack
```
I asked my students to input correct URLs into Elements that are now supposed to appear under "Links". None of the URLs have labels, and tend to be pretty long. Any recommendations on how to display them?
```

You can see an example of some links for Quinn above, the longest being 85 characters in length.

One possibility is we could display links over a certain threshold with the domain followed by `...`, ie `https://scholar.google.com/...`.

**Comment by wrenaria** [comment]
@UcDust Can you hide the `https://` and `https://www.` portion of website addresses? It's unnecessary to show in this context and will help make scanning the list easier for users. 

I am also open to the ellipses solution for super long URLs in addition to the above, but would want to be long enough to go beyond `.com`, `.edu`, etc. so that if there are multiple URLs from the same domain it's clear that they are not the same link. I'm not sure what the character count threshold for that would be.

**Comment by qjhart** [comment]
CDL elements allows you to identify your link type with the following types:
Blog,Company,,Department,figshare,Google Scholar,Laboratory,LinkedIn,Mendeley,Other,Personal,Portfolio,ResearchGate,RSS Feed,Twitter

These are carried through into the experts document via additional types for the links: 

```json
"hasURL": [
{
"@id": "expert/66356b7eec24c51f01e757af2b27ebb8#vcard-oap-1-web-4",
"@type": [
"URL",
"ucdlib:URL_department"
],
"rank": 4,
"url": "https://library.ucdavis.edu/"
},
{
"@id": "expert/66356b7eec24c51f01e757af2b27ebb8#vcard-oap-1-web-0",
"@type": "URL",
"rank": 0,
"name": "Evaporation (Meteorology)",
"url": "http://id.worldcat.org/fast/917080"
},
{
"@id": "expert/66356b7eec24c51f01e757af2b27ebb8#vcard-oap-1-web-5",
"@type": [
"URL",
"ucdlib:URL_company"
],
"rank": 5,
"url": "https://ucdavis.edu/"
},
{
"@id": "expert/66356b7eec24c51f01e757af2b27ebb8#vcard-oap-1-web-1",
"@type": [
"URL",
"ucdlib:URL_department"
],
"rank": 1,
"name": "Library Bio",
"url": "https://library.ucdavis.edu/person/quinn-hart/"
},
{
"@id": "expert/66356b7eec24c51f01e757af2b27ebb8#vcard-oap-1-web-2",
"@type": "URL",
"rank": 2,
"url": "https://library.ucdavis.edu/online-strategies"
},
{
"@id": "expert/66356b7eec24c51f01e757af2b27ebb8#vcard-oap-1-web-3",
"@type": [
"URL",
"ucdlib:URL_googlescholar"
],
"rank": 3,
"url": "https://scholar.google.com/citations?user=Od5weOkAAAAJ&hl=en&inst=9081605168663377197"
}
]```

**Comment by UcDust** [comment]
We're going to add custom icons for the following link types (if they exist):

_Font Awesome:_
Google Scholar: https://fontawesome.com/icons/google-scholar?f=brands&s=solid
LinkedIn: https://fontawesome.com/icons/linkedin?f=brands&s=solid
Mendeley: https://fontawesome.com/icons/mendeley?f=brands&s=solid
RSS Feed: https://fontawesome.com/icons/square-rss?f=classic&s=solid
ResearchGate: https://fontawesome.com/icons/researchgate?f=brands&s=solid
Twitter: https://fontawesome.com/icons/x-twitter?f=brands&s=solid

_Academicons has one for figshare_
