### ISSUE TITLE
Users can remove themselves from Aggie Experts

### ISSUE THREAD

**Issue by Vensberg** [ucd-library/aggie-experts#458]
**Description:**
As a regular user with an Aggie Experts profile, I want to be able to opt out of participating and have all my information removed from the system.

**Acceptance criteria:**

There needs to be a way for me to easily opt out.
When I remove myself from the platform, my publications and grants will no longer be retrieved.
Searches for my name or works or grants will not return results (unless the works have co-authors in AE or the grants have personnel in AE)
The user profile in Elements will be set to "internal".

**Comment by qjhart** [comment]
When a user, eg [Garrity](https://sandbox.experts.library.ucdavis.edu/expert/Uvk6UYrd) goes to their page, they see a trash icon.  

![image](https://github.com/ucd-library/aggie-experts/assets/344953/d0f63ad4-d8d1-4f40-be23-530201f2f728)

Clicking this, this see a modal explaiing what will happen on accept

**Comment by qjhart** [comment]
Navigating to their CDL site, you will see their profile is now set to internal

![image](https://github.com/ucd-library/aggie-experts/assets/344953/b6afb317-9ff3-4a45-b8ca-e6f99d45a1b0)
