### ISSUE TITLE
"My Profile" not always loading

### ISSUE THREAD

**Issue by Vensberg** [ucd-library/aggie-experts#5]
**Describe the bug**
When I click on "My Profile" while viewing someone else's profile, I get a blinking "loading" message and nothing loads. It stays there after a reload or a second attempt to click on "My Profile". If I am in a specific subject (e.g. "Mathematical sciences"), my profile doesn't load either, but there is no loading message. The subject page just reloads. The same thing happens when I try to navigate to my profile from the landing page of a publication. I don't have this problem if I start from the home page, landing pages of People, Subjects and Works.

**To Reproduce**
1. Go to any other person's profile
2. Go up to your own name in the upper right-hand corner
3. Click on "My Profile"

**Expected behavior**
The profile page should load.

**Desktop (please complete the following information):**
 - Windows 10
 - Firefox
 - 85.0.1

**Comment by jrmerz** [comment]
which instance/url?

**Comment by Vensberg** [comment]
https://rc.experts.ucdavis.edu/
