### ISSUE TITLE
Support for the `availability` label?

### ISSUE THREAD

**Issue by qjhart** [ucd-library/aggie-experts#537]
### Discussed in https://github.com/ucd-library/aggie-experts/discussions/87

<div type='discussions-op-text'>

<sup>Originally posted by **qjhart** March 22, 2023</sup>
Elements comes with the option of including the `availability` attribute.  This attribute could help users discover experts based on their willingness to be contacted regarding these items. 

The definition for this label scheme is:

_This scheme allows you to describe what kinds of opportunities you are interested in being contacted about such as industry projects, mentoring or media enquiries. Once captured this information can (subject to configuration) be reused in a number of ways including on your public profile._

In order to support this, we'd need to move into production elements, and update our UI.  
</div>

**Comment by qjhart** [comment]
It was decided that because there were required items not in the current ~availability~ scheme, rather then work to include them, we'd make an Aggie Experts exclusive set of these terms.  This is currently named *Availability (Aggie Experts) scheme*  

We have the following codes

Label Value | Code | Description
---|---|---
Career advice | 9 | Available for mentoring: career advice
Collaborative projects | 1 |Available for collaborative project work
Community partnerships | 12 | Available for engaging in community projects
Industry Projects | 11 | Available for Industry Projects
Join a web conference as a panellist or speaker | 10 | Availability to organize or join a web conference as a panellist or speaker
Masters Research or PhD student supervision | 3 | Available to supervise Masters Research or PhD students
Media enquiries | 4 | Available for media enquiries
Membership of an advisory committee | 2 | Avaliable to be a member of an advisory committee
Mentoring (long-term) | 6 | Available for long-term mentoring
Mentoring (short-term) | 8 |Available for short-term mentoring
Teaching provision | 5 | Available for teaching
Technical support | 7 | Available for mentoring: technical support

However, the plan is to have <6 items. Not all of these are ever planned to be used in AE, so we need to reduce this to the ones in use by AE.   The original source of the extended list is described below:

![image](https://github.com/ucd-library/aggie-experts/assets/344953/759b0d9c-3a47-4e4f-959a-97e933669379)

**Comment by Vensberg** [comment]
It is useful to keep a shared core in case another campus starts using the availability labels.

**Comment by qjhart** [comment]
We don't use codes
