### ISSUE TITLE
What to do with citations that have arrays of issued dates (multiple DOI's assigned to publication)

### ISSUE THREAD

**Issue by UcDust** [ucd-library/aggie-experts#540]
@Vensberg sometimes a citation ends up with arrays of titles and dates. AFAIK, this only happens when elements erroneously adds to very different (usually) records to the same DOI.  I can't think of a good way to disambiguate these. 

I think I will suggest to @UcDust that we should just choose the first item, but make them `visible=false`  These are  the items that we reviewed in the `fin/admin` section, where I said the interface needs work but you said it was okay.  Now's the time to review that as well.

**Comment by UcDust** [comment]
@Vensberg 
We could also choose the first date and display in the ui under that date, but have a label indicating the other date as well, and that perhaps the data needs to be fixed. This could be a label only to the admins as well, like when editing the page or editing the list of works.

For titles, we could combine them or use the first.

**Comment by Vensberg** [comment]
Can you apply the "misformated citation, contact admin" label here? There isn't a good default solution to the handful of examples I've seen.

**Comment by UcDust** [comment]
@Vensberg 
Were you wanting the _misformated citation_ label to show up only for the expert (and admins) when they're editing their citations? But for the public view, we would hide these works?

**Comment by Vensberg** [comment]
@UcDust, that sounds good.

**Comment by UcDust** [comment]
@Vensberg 

This is the design Kimmy came up to show the mis-formatted works and grants. It will show up only on the _Edit_ pages.
![Image](https://github.com/user-attachments/assets/5b889268-3d88-4f6f-8933-82ce2af75bff)
