### ISSUE TITLE
[FEAT] Create grant detail page and link to it

### ISSUE THREAD

**Issue by UcDust** [ucd-library/aggie-experts#558]
Links to the page should be where they're listed, on the expert profile and the grant list (edit?) pages.

<img width="437" alt="Screenshot 2024-07-18 at 09 30 27" src="https://github.com/user-attachments/assets/3d2f17ab-1098-4fdb-a74c-54ffbb77fc21">

**Comment by UcDust** [comment]
[This PR](https://github.com/ucd-library/aggie-experts/pull/541) has the index to use.

**Comment by qjhart** [comment]
@UcDust the initial grant-index is in place, not search or browse

``` bash
http http://localhost/api/grant/ark%3A%2F87287%2Fd7gt0q%2Fgrant%2FK326418-108231 Cookie:"fin-jwt=$jwt"
```

**Comment by UcDust** [comment]
@qjhart 

It looks like hiding/showing `grants` as well as `works` isn't working any longer. I wonder if it could be because of the changes to how the _relationships_ are tied to the expert in fcrepo? 

The grant visibility issue is more obvious since the `grant_role` model was mostly removed, and the `patch` function doesn't exist any longer. Issue when changing visibility for `works` is a little more surprising. It's also interesting that the graph data that comes back in the api still has references to `relationship`, although that's removed from the arks in fcrepo now. 

Maybe we can chat more on how this should function now.

**Comment by UcDust** [comment]
@qjhart 

Also if you'd like to look at the ui, I made https://github.com/ucd-library/aggie-experts/pull/613 which has the most recent client code. 

It doesn't have `Purpose`, but if that's ready, could you point me to a grant that has that in the data?
