### ISSUE TITLE
Update harvest image / and queries to include better title names

### ISSUE THREAD

**Issue by qjhart** [ucd-library/aggie-experts#561]
We use a set  of titles from UCOP.  The academic titles are located at [ucop](https://www.ucop.edu/academic-personnel-programs/compensation/academic-ctos-titles-and-title-codes/index.html).

Occasionally, I download these in [academic_titles.txt](https://github.com/ucd-library/aggie-experts/tree/dev/harvest/vocabularies/experts.ucdavis.edu%252Fucop), and then use a Makefile to create some linked data, that is added to the harvester, via the (fuseki config)[https://github.com/ucd-library/aggie-experts/blob/9e29a8786cafd7f5619482eb3760e36a3651dbd5/harvest/fuseki/configuration/experts.ttl.tmpl#L61].

@Vensberg had a student take that list, and create more readable titles in a (spreadsheet)[https://docs.google.com/spreadsheets/d/18eyWMu5jLDCk4-j54u247FwgwI1JrpxUiop7vnhHSP0/edit?usp=sharing].  The first thing to do would be to add an additional column to the academic.txt file that includes these titles.  Then modify the Makefiile, to add that to the JSON that's imported into the positions graph.  

You may want create a `*.tsv` file from the spreadsheet and use that directly, by modifing the Makefile.  I used text, cause it came from the PDF file.

**Comment by qjhart** [comment]
@rakunkel-ucd the next step is to include that in expert feed.  There are a number of places to do this, however the best  place (for the upcoming experts-cache fix) is probably the the (iam construct)[https://github.com/ucd-library/aggie-experts/blob/9e29a8786cafd7f5619482eb3760e36a3651dbd5/harvest/harvest/iam/rq/experts.rq#L145] where instead of  using the title from the IAM feed, you match the title code, and grab the better title from the positions graph

**Comment by rakunkel-ucd** [comment]
Is the ucop title list only downloadable as pdf?
