### ISSUE TITLE
Title and department don't appear on the profile

### ISSUE THREAD

**Issue by Vensberg** [ucd-library/aggie-experts#565]
David Lubarsky does not have his name and title appear in the bio portion of the AE profile

**To Reproduce**

1. Go to [his profile](https://experts.ucdavis.edu/expert/El3y3hpI)
2. There is no bio section, it immediately presents his web urls
3. The data are in the api
4. The title and department appear under the name in Search; the data are only missing in the profile bio

**Expected behavior**
The title and department should appear as some form of "CEO MED CTR, UCD Health Administration"

**Comment by UcDust** [comment]
@qjhart @Vensberg 

It looks like this experts' `contactInfo` doesn't have any links which have `isPreferred: true`, so we're filtering everything from the ui. 

Does that filtering logic need to change in the client, or perhaps another approach?

**Comment by qjhart** [comment]
Hmm, yes. This seems to be an error in the harvest code We have this [code](https://github.com/ucd-library/aggie-experts/blob/1111c0610e00eca8204d894d7f527f01df53989d/harvest/harvest/iam/rq/experts.rq#L149)

```sparql
OPTIONAL {
            ?s iam:directory/iam:listings/iam:title [].
            bind(true as ?has_odr)
          }
```
But for this user, they set their  one ODR entry to  deptWWWFlag: "N", which means we don't include the (preferred) entry.


```json
       "listings": [
          {
            "listingOrder": 1,
            "deptCode": "8316",
            "deptName": "Administration",
            "deptWwwFlag": "N",
            "deptUcdFlag": "Y",
            "title": "Vice Chancellor & CEO",
            "titleWwwFlag": "Y",
            "titleUcdFlag": "Y",
            "website": null,
            "websiteWwwFlag": "N",
            "websiteUcdFlag": "N",
            "email": "vclubarsky@ucdavis.edu",
            "emailWwwFlag": "Y",
            "emailUcdFlag": "Y",
            "location": null,
            "device": null,
            "createDate": "2018-06-08 02:26:25",
            "modifyDate": "2023-10-30 10:01:12"
          }
```
