### ISSUE TITLE
[FEAT] Update browse experts page to filter by faculty/non-academic

### ISSUE THREAD

**Issue by UcDust** [ucd-library/aggie-experts#606]
The browse experts page needs to be updated to filter by all experts, only faculty, or only non-academic. Besides the ui and api changes, we'll have to modify the harvest script as well.

![image](https://github.com/user-attachments/assets/890beccb-08b7-4444-8a4f-6b3ec796b3f3)

**Comment by Vensberg** [comment]
@UcDust , we don't have a good use case at this time to filter on academic/ non-academic. Maybe once we grow beyond federation, but even then I am not sure/ Let's close this issue as not planned.
