### ISSUE TITLE
[BUG] Should experts that aren't currently staff be included if they have an external affiliation? 

### ISSUE THREAD

**Issue by qjhart** [ucd-library/aggie-experts#614]
The user with iamID = 1000140132 has na ppsAssocitions.  I notice they have isStaff=true, and isExternal=true.  Can you describe the association of users like this to Davis ?

``` json
  {
    "iamId": "1000140132",
    "ppsId": null,
    "employeeId": null,
    "isStudent": false,
    "isStaff": true,
    "isExternal": true,
    "ppsAssociations": null,
    "sisAssociations": null,
  }
```

From IET: 

Hi Quinn,

Thank you for contacting IT Express. It looks like this user is currently just a temporary affiliate sponsored by the Earth and Planetary Sciences department but has had on and off staff/faculty status with UC Davis over the past few years.  

Please let me know if you need any additional information.

**Comment by qjhart** [comment]
@Vensberg whatever you decide, we need to modify the code a bit, so assign me and send me a note in the issue.

**Comment by Vensberg** [comment]
@qjhart, it looks like this change in IAM triggers deletion of Elements data, so there is nothing for us to work with.
