### ISSUE TITLE
[FEAT] All Aggie Expert Records have a last modified date enabling search for Modified Since

### ISSUE THREAD

**Issue by rakunkel-ucd** [ucd-library/aggie-experts#639]
Enable searches for objects that are new or have been modified since a specified date.

**Comment by qjhart** [comment]
If you look at the kibana indexes, you will see that Justin's fin import tool adds a `_` parameter for system components.  One component of that is the `_.updated` field.  Where I get confused about this, is that it's part of the `@graph[]` component only, were I imagine we'd want that at the document level.  Also, it's not on every node only the `root` node (not sure how that's described) I think we want  tp promoate that to the document, and update it whenever enay node is updated.  We can see about updating fin, or rewriting the function that puts the docs in.

**Comment by qjhart** [comment]
@rakunkel-ucd can you try and track down where that's added in the fin code?

**Comment by rakunkel-ucd** [comment]
The solution is to add a ingest pipeline to the ES instance that can be used with all indexed to add a "modified-date" field at the document level. It can be added using a HTTP POST. Note that the ingest pipeline must be added BEFORE any indexes are created and before any documents are ingested. 

The method to create the ingest pipeline is to define it as part of the docker-compose.yaml based deployment. An init cURL script script is used to POST the pipeline when the ES instance is ready.
