### ISSUE TITLE
[bug] fix `hasAvailability`

### ISSUE THREAD

**Issue by qjhart** [ucd-library/aggie-experts#644]
The current `hasAvailability` only propoagates the experts' `hasAvailability` urls to the document.   setup.  I propose that we more accurately represent this with the preferred label as well, so...

```json
{
  "_id": "expert/LDdgBTXN",
  "_version": 74,
  "_source": {
    "@id": "expert/LDdgBTXN",
    "@context": "http://localhost/api/schema/1/context.jsonld",
    "@graph": [],
   "hasAvailability": [{
          "skos:prefLabel": "Collaborative projects",
          "availabilityOf": "expert/LDdgBTXN",
          "@type": "Concept",
          "@id": "ark:/87287/d7mh2m/keyword/c-ucd-avail/Collaborative%20projects",
          "skos:inScheme": {
            "@id": "ark:/87287/d7mh2m/keyword/c-ucd-avail/"
          }
        }],
        "orcidId": "0000-0001-9829-8914",
        "@id": "expert/LDdgBTXN"
        }
```

This is more standard with our practice of just promoting `@graph` components to the document level. 
Furthermore, we base the `hasAvailability` index in elastic search on the `prefLabel`  so that filters will look like

```httpd
/search?q=hart&hasAvailability=Collaborative%20projects
```

And finnally our schema will promote `skos:prefLabel` to `prefLabel`

**Comment by qjhart** [comment]
@UcDust does this seem reasonable? UI effects should be limited to your search formulation only, AFAIK.

**Comment by UcDust** [comment]
@qjhart yea this seems like it would work.
