### ISSUE TITLE
Users will be able to download their search results

### ISSUE THREAD

**Issue by Vensberg** [ucd-library/aggie-experts#77]
The download file should be a CSV with the following columns
* Type of result (person, work, grant)
* expert's name
* type of field in which the keyword appears
* field content
* role in relation to the field (e.g. if the field is the title/abstract of a publication, list whether this is a first or last author; if it is a grant, list the role; no role is needed for subject keywords and bios)
* AE profile landing page
* expert's website
* expert's email

**Comment by Vensberg** [comment]
From conversations with @qjhart it appears we can't distinguish the field which the keyword hit. In that case, have the entire citation of the work or grant, and collapse together.
* type of field in which the keyword appears
* field content
This means that there will be multiple entries per one person with multiple works/grants.

**Comment by UcDust** [comment]
A comment earlier between @Vensberg @qjhart, just don't want to lose track if slack is purged.

```
Field would be equivalent to work type (unless at some point it is possible to pinpoint that the search hit the abstract or the title or the journal name--but no need to worry about this in the near term). Putting in the entire APA citation is appropriate. Then role will be--author, first author, last author.
When we move to grants, the filed content will have the citation of the grant, and then the role will be PI, coPI, key personnel, etc (depending on what we can get from AEnterprise)
```

**Comment by Vensberg** [comment]
@Vensberg , @wrenaria will work on the CSV columns

**Comment by UcDust** [comment]
@Vensberg 
You mentioned earlier today to mention you on this task regarding an issue with the search results download. Can you let me know what needs to be changed?

**Comment by Vensberg** [comment]
There is one case when I download the csv for Atwill, Edward, and his urls are separated the following way: url1; [space] url2; [tab] url3. I don't see that in two other examples. So I think we can call this done and just keep an eye for odd tabs occurring elsewhere.

**Comment by Vensberg** [comment]
We will revisit as search evolves
