### ISSUE TITLE
Visitors of the Public Engagement website https://publicengagement.ucdavis.edu/public-scholars will be able to see the scholars' departmental affiliations, publications and grants from the most recent 5 years, research are keywords, and bios and websites if those are available

### ISSUE THREAD

**Issue by Vensberg** [ucd-library/aggie-experts#81]
In this stage, PSE will send us the list of their fellow, and we will provide the fields listed as a spreadsheet.

- [x] Enrich the publication data in Elements
- [x] #84
- [x] #83
- [ ] Send the spreadsheet
- [ ] Follow up for feedback

**Comment by qjhart** [comment]
@Vensberg the [spreadsheet](https://docs.google.com/spreadsheets/d/1frAQcH216DZfO7_J2EdQNR0qwUEWPYdTK7mHRKHuGUY/edit?usp=sharing) should be complete. 

I implore you to please include communication of the discussions #87 and #88 in your list above
