### ISSUE TITLE
PSE shared spreadsheet has individual sheets for publications  and grants

### ISSUE THREAD

**Issue by qjhart** [ucd-library/aggie-experts#83]
The spreadsheet to share with the PSE will include separate sheets for publications and grants.  They will be cross referenced with people via email:

Publications will have : 

```text
| email | year | title | journal | DOI | citation |
```

Grants will have: 

```text
email | award date | title | Agency | citation? 
```

Citations will be simple  text representations.

## Results
[Spreadsheet](https://docs.google.com/spreadsheets/d/1frAQcH216DZfO7_J2EdQNR0qwUEWPYdTK7mHRKHuGUY/edit?usp=sharing)

**Comment by Vensberg** [comment]
Citation: Authors. Title. Year. Journal, Volume(Issue), Page.

**Comment by qjhart** [comment]
From Karen Chan <[kpichan@ucdavis.edu](mailto:kpichan@ucdavis.edu)>
  
 Thank you so much for meeting with us last week. Here is the [spreadsheet](https://ucdavis.box.com/s/n8rhd3sfp87pknhsf1e8g6ie8vj6pcwn) of PSE's affiliates with their email addresses. Please feel free to let me know if you have any questions or if you need any additional information.

**Comment by qjhart** [comment]
# Table of Contents

1.  [Creating Summary Queries](#org517efd7)
    1.  [Grants](#org7f6698d)
    2.  [Citations](#org21ba5d1)


<a id="org517efd7"></a>

# Creating Summary Queries


<a id="org7f6698d"></a>

## Grants

    PREFIX vivo: <http://vivoweb.org/ontology/core#>
    PREFIX grant: <http://experts.ucdavis.edu/grant/>
    PREFIX obo: <http://purl.obolibrary.org/obo/>
    PREFIX vcard: <http://www.w3.org/2006/vcard/ns#>
    PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
    prefix ucdrp: <http://experts.ucdavis.edu/schema#>
    PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
    #Authors. Title. Year. Journal, Volume(Issue), Page.
    
    select ?email ?begin ?title ?sponsor ?citation
    #describe ?grant ?start ?end
    where {
      ?user vivo:relatedBy ?grant;
    	.
      ?grant a vivo:Grant;
    	 rdfs:label ?title;
    	 .
      OPTIONAL {
        ?grant vivo:sponsorAwardId ?award_id.
        }
      OPTIONAL {
        ?grant vivo:assignedBy/rdfs:label ?sponsor.
        }
    
      OPTIONAL {
        ?grant vivo:dateTimeInterval ?date.
        ?date vivo:start/vivo:dateTime ?start.
        bind(str(year(xsd:date(?start))) as ?begin)
    
        OPTIONAL {
          ?date vivo:end/vivo:dateTime ?end.
          bind(str(year(xsd:date(?end))) as ?e)
          filter(?begin != ?e)
        }
        bind(concat(?begin,coalesce(concat('-',?e),'')) as ?dur)
      }
    
      ?user a ucdrp:person;
    	obo:ARG_2000028 ?contact;
    	.
      ?contact ucdrp:identifier "pps-1";
    	   vcard:hasEmail/vcard:email ?email;
    	   .
      bind
      ( concat
       (?title,
        coalesce(concat('. ',?dur),''),
        coalesce(concat('. ',?sponsor),''),
        coalesce(concat('. ',?award_id),'')
        ) as ?citation)
    } order by ?email


<a id="org21ba5d1"></a>

## Citations

    PREFIX vivo: <http://vivoweb.org/ontology/core#>
    PREFIX grant: <http://experts.ucdavis.edu/grant/>
    PREFIX work: <http://experts.ucdavis.edu/work/>
    PREFIX obo: <http://purl.obolibrary.org/obo/>
    PREFIX vcard: <http://www.w3.org/2006/vcard/ns#>
    PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
    PREFIX bibo: <http://purl.org/ontology/bibo/>
    PREFIX bib: <http://zeitkunst.org/bibtex/0.1/bibtex.owl#>
    prefix ucdrp: <http://experts.ucdavis.edu/schema#>
    
    #Authors. Title. Year. Journal, Volume(Issue), Page.
    #describe ?work ?authorship ?contact ?vcard ?name
    select ?email ?year ?title ?journal ?doi ?citation
    where {
      ?work a ucdrp:work;
    	rdfs:label ?title;
    	.
    
      OPTIONAL {
        ?work vivo:dateTimeValue/vivo:dateTime ?date.
        bind(str(year(?date)) as ?year)
      }
      OPTIONAL {
        ?work bibo:journal ?journal.
      }
      OPTIONAL {
        ?work bibo:doi ?doi.
      }
      OPTIONAL {
        ?work bibo:volume ?volume.
        OPTIONAL {
          ?work bibo:issue ?issue.
        }
      }
    
      OPTIONAL {
        ?work bibo:pageStart ?start;
    	  .
        OPTIONAL {
          ?work bibo:pageEnd ?end;
    	    .
        }
      }
    
      ?work vivo:relatedBy/vivo:relates/obo:ARG_2000028 ?contact;
    	.
      ?contact ucdrp:identifier "pps-1";
    	   vcard:hasEmail/vcard:email ?email;
    	   .
      {
        select ?work (group_concat(?author; separator=', ') as ?authors)
        WHERE {
          ?work vivo:relatedBy ?authorship;
    	    .
          ?authorship vivo:relates ?vcard;
    		  vivo:rank ?rank;
        .
          ?vcard a vcard:Individual;
    	     vcard:hasName ?name;
    	     .
          ?name vcard:familyName ?family.
          OPTIONAL {
    	?name vcard:givenName ?given
          }
          bind(concat(?family,coalesce(concat(' ',?given),'')) as ?author)
          #      bind(concat(str(?rank),'-',?family,coalesce(concat(' ',?given),'')) as ?author)
        } group by ?work order by ?work ?rank }
    
      bind(
           concat(
    	      ?authors,". ",
    	      ?title,". ",coalesce(concat(?year,". "),""),coalesce(?journal,''),
    	      coalesce(concat(', ',?volume,coalesce(concat('(',?issue,')'),'')),''),
    	      coalesce(concat(', ',?start), coalesce(concat('-',?end),'')),
    	      coalesce(concat('. DOI:',?doi),'')
    	      )
           as ?citation)
    
    } order by ?email
