### ISSUE TITLE
Create and populate database with the PSE emails

### ISSUE THREAD

**Issue by qjhart** [ucd-library/aggie-experts#84]
Similar to other projects, we will create a special PSE V1 (fuseki) database.  This will get the most current CDL and grants data. From this will will build a spreadsheet to identify the type of data that we have in Aggie Experts.

One sheet will have information regarding the scholars.  This will include: 

```text
| email | best-title | department | research_summary | teaching | keywords | ?
```

Keywords will be separated with a semi-colon;

Websites will be a separate sheet

```text
| email | source | website | 
```

**Comment by qjhart** [comment]
# Table of Contents

1.  [websites](#org9512992)


<a id="org9512992"></a>

# websites

Websites are always located within a users vcard.  To track where it comes
from, let&rsquo;s include the identifier for the vcard as well.  If a label exists
add that too

    PREFIX vivo: <http://vivoweb.org/ontology/core#>
    PREFIX grant: <http://experts.ucdavis.edu/grant/>
    PREFIX obo: <http://purl.obolibrary.org/obo/>
    PREFIX vcard: <http://www.w3.org/2006/vcard/ns#>
    PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
    prefix ucdrp: <http://experts.ucdavis.edu/schema#>
    PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
    
    select ?email ?id ?url ?label
    #describe ?url
    WHERE {
      ?user obo:ARG_2000028 ?pps.
      ?pps ucdrp:identifier 'pps-1';
    	vcard:hasEmail/vcard:email ?email;
     .
      
      ?user obo:ARG_2000028 ?card.
      ?card vcard:hasURL ?link; 
    	ucdrp:identifier ?id;
     .
     ?link vcard:url ?url.
      OPTIONAL {
        ?link rdfs:label ?label.
      }
    #  filter(! regex(?id,'odr'))
    } order by ?email ?id ?url

**Comment by qjhart** [comment]
# Table of Contents

1.  [Biographical Info](#orgfa1f2f8)


<a id="orgfa1f2f8"></a>

# Biographical Info

    PREFIX vivo: <http://vivoweb.org/ontology/core#>
    PREFIX grant: <http://experts.ucdavis.edu/grant/>
    PREFIX obo: <http://purl.obolibrary.org/obo/>
    PREFIX vcard: <http://www.w3.org/2006/vcard/ns#>
    PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
    prefix ucdrp: <http://experts.ucdavis.edu/schema#>
    PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
    
    select ?email ?name ?title ?org ?source 
    # describe ?card ?name
    WHERE {
      ?user obo:ARG_2000028 ?pps.
      ?pps ucdrp:identifier 'pps-1';
    	vcard:hasEmail/vcard:email ?email;
     .
    
      {
        select ?user (min(?rank) as ?best)
        WHERE {
          ?user obo:ARG_2000028 ?card.
    	    ?card ucdrp:identifier ?id;
    	   vivo:rank ?rank;
        .
        } group by ?user
      }
    
      ?user obo:ARG_2000028 ?card.
      ?card vivo:rank ?best;
    	vcard:hasName ?names;
    	vcard:hasOrganizationalUnit/vcard:title ?org;
     vcard:hasTitle/vcard:title ?title;
    	ucdrp:identifier ?source;
     .
    
      ?names vcard:familyName ?family.
      OPTIONAL {
        ?names vcard:givenName ?given.
      }
      OPTIONAL {
        ?names vcard:middleName ?middle.
      }
      bind(concat(?family,
    	      coalesce(concat(', ',?given,
    			      coalesce(concat(' ',?middle),''),''))) as ?name)
    
    
    } order by ?email

**Comment by qjhart** [comment]
@Vensberg I left off the teaching summaries, etc because their were none filled out.  Let me know if your students have actually filled those out, and they are missing for some reason (w/ example)

**Comment by Vensberg** [comment]
No, they are only working on author ids.

**Comment by qjhart** [comment]
@Vensberg you are correct, if there was any change in values, that would show multiple rows.  I've added an updated citation set to the [spreadsheet](https://docs.google.com/spreadsheets/d/1frAQcH216DZfO7_J2EdQNR0qwUEWPYdTK7mHRKHuGUY/edit?usp=sharing).

I did this just by choosing a parameter, min(year),max(title, doi)  for each work.  That's not great, but it's not how we are doing v2 anyways.

**Comment by qjhart** [comment]
@Vensberg 

   ceambrozek@ucdavis.edu	=> cdl elements is-login-allowed = "false" so not included
   iher@ucdavis.edu	Irva	Hertz-Picciotto =>  ihp@ucdavis.edu
   Evasile@ucdavis.edu	Elizabeth	Vasile  => evasile@ucdavis.edu,  No works however
   mxrios@ucdavis.edu	Michael Rios -> viceprovostpse@ucdavis.edu

New CSV included at
[new.zip](https://github.com/ucd-library/aggie-experts/files/11446494/new.zip)
