### ISSUE TITLE
Compare IAM and CDL users

### ISSUE THREAD

**Issue by qjhart** [ucd-library/aggie-experts#85]
Our IAM profiles identifies faculty and staff.  In addition to that we have a list of title groups for users. CDL, by contrast uses this list of title code groups to identify who is and isn't included the the OA policy guidelines.  We want to compare the differences between these two methods, and come to aggreement on who gets added to the system.

**Comment by qjhart** [comment]
@Vensberg for the purposes of V2 we are using the list of senate faculty as described be CDL group=438 correct? This is for a later date?

**Comment by Vensberg** [comment]
@qjhart created UC Davis (aggie-experts) Group ID: 1547 to include senate non-emeriti faculty for version 2.0 roll-out.
